In [304]:
using Pkg
Pkg.activate(".")

  Activating project at `c:\Users\fefif\Desktop\PhD\Progetti\MatrixProductBP.jl`


In [305]:
using Revise
using MatrixProductBP, MatrixProductBP.Models
using Graphs, IndexedGraphs, Statistics, Random, LinearAlgebra, TensorTrains, SparseArrays
import ProgressMeter; ProgressMeter.ijulia_behavior(:clear)
using TensorTrains: summary_compact
using SparseArrays
using JLD2
include("bp_fourier.jl");

In [306]:
seed = 1
rng = MersenneTwister(seed)

T = 4
# N = 3
# A = [0 1 1; 
#      1 0 0;
#      1 0 0;]
# N = 4
# A = [0 1 1 1;
#      1 0 0 1;
#      1 0 0 1;
#      1 1 1 0]
# !!! Here the calculations are wrong for edge 1->2 !!!
# N = 5
# A = [0 1 1 1 1; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0]
# N = 6
# A = [0 1 1 1 0 0; 
#      1 0 0 0 1 0; 
#      1 0 0 0 0 1; 
#      1 0 0 0 0 0; 
#      0 1 0 0 0 0; 
#      0 0 1 0 0 0]
# N = 7
# A = [0 1 1 1 1 0 1;
#      1 0 0 0 1 0 0; 
#      1 0 0 0 0 1 0; 
#      1 0 0 0 0 0 0; 
#      1 1 0 0 0 0 0; 
#      0 0 1 0 0 0 0; 
#      1 0 0 0 0 0 0]
# N = 8
# A = [0 1 1 1 0 0 1 0;
#      1 0 0 0 1 0 0 1; 
#      1 0 0 0 0 1 0 0; 
#      1 0 0 0 0 0 0 0; 
#      0 1 0 0 0 0 0 0; 
#      0 0 1 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0;
#      0 1 0 0 0 0 0 0]

# g = IndexedBiDiGraph(A)

N = 10
c = 3
gg = erdos_renyi(N, c/N; seed)
g = IndexedBiDiGraph(gg)
A = zeros(Int,N,N)
for i in CartesianIndices(A)
     if !iszero(g.A[i])
         A[i] = 1
     end
end
β = 1.0
J = 1
h = 0.0
m⁰ = 1.0
K = 100

svd_trunc=TruncBond(4)

A

10×10 Matrix{Int64}:
 0  0  0  0  0  0  1  1  0  1
 0  0  1  0  0  0  1  0  0  0
 0  1  0  1  0  1  1  0  1  0
 0  0  1  0  1  1  0  0  0  0
 0  0  0  1  0  0  1  1  0  0
 0  0  1  1  0  0  0  1  0  1
 1  1  1  0  1  0  0  1  1  1
 1  0  0  0  1  1  1  0  0  0
 0  0  1  0  0  0  1  0  0  0
 1  0  0  0  0  1  1  0  0  0

In [307]:
w = [fill(IntegerGlauberFactor([J*A[j,i] for j in inneighbors(g,i)], h, β), T+1) for i in vertices(g)]
ϕᵢ = [t == 0 ? [(1-m⁰)/2, (1+m⁰)/2] : ones(2) for t in 0:T]
bp = mpbp(g, w, fill(2,N), T; ϕ=fill(ϕᵢ,N))

for μ in bp.μ
    for a in μ
        a.=rand.(rng)
        # a.=1.0
    end
end
bp_fourier = deepcopy(bp)
iterate!(bp, maxiter=1; svd_trunc)

# msg = deepcopy(bp.μ)
# jldsave("messages.jld2"; msg)

# bp_fourier = deepcopy(bp)
iterate_fourier!(bp_fourier,K, maxiter=1, σ=1/100; svd_trunc)
;

In [308]:
for t in 1:T+1
    # display(t)
    # display(bp.μ[7][t])
    # display(bp_fourier.μ[7][t])
end

In [309]:
iterate!(bp,maxiter=5; svd_trunc)

Running MPBP: iter 2    Time: 0:00:00

Running MPBP: iter 3    Time: 0:00:00

Running MPBP: iter 4    Time: 0:00:00

Running MPBP: iter 5    Time: 0:00:01

(5, CB_BP{ProgressMeter.ProgressUnknown, MatrixProductBP.var"#153#156"}(ProgressMeter.ProgressUnknown(false, false, 0, ProgressMeter.ProgressCore(:green, "Running MPBP: iter", 0.1, true, 0, VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}(IOContext(Base.PipeEndpoint(Base.Libc.WindowsRawSocket(0x0000000000000314) open, 0 bytes waiting)), VSCodeServer.io_send_callback), false, 1, 5, ReentrantLock(nothing, 0x00000000, 0x00, Base.GenericCondition{Base.Threads.SpinLock}(Base.IntrusiveLinkedList{Task}(nothing, nothing), Base.Threads.SpinLock(0)), (2278191112456, 2278191025064, 140732428818288)), 2, 5, true, false, 1.734690598525e9, 1.734690599563e9, 1.734690598525e9)), [[[2.0000000000000004, 1.3962748922517556, 1.2512455982135078, 1.4398183349948888, 1.254966312745844], [2.0, 1.1624517352436172, 1.0571995336666546, 1.9862614107620502, 1.289571470828798], [2.0, 1.8776458571167745, 1.9307376060121948, 1.3307461346186709, 1.5886285208426656], [2.0, 1

In [310]:
iterate_fourier!(bp_fourier,K, maxiter=5, σ=1/100; svd_trunc)
;

In [311]:
import MatrixProductBP: marginalize
function marginalize(A::MPEM2{F}, var) where F
    if var==1
        return MPEM1{F}([@tullio b[m, n, xi] := a[m, n, xi, xj] for a in A]; z = A.z)
    elseif var==2
        return MPEM1{F}([@tullio b[m, n, xj] := a[m, n, xi, xj] for a in A]; z = A.z)
    end
end;

In [312]:
er = []
ptr = []
for e in edges(bp.g)
    μ_marg = marginalize(bp.μ[idx(e)],1)
    margs = marginals(μ_marg)
    μ_fourier_marg = marginalize(bp_fourier.μ[idx(e)],1)
    margs_fourier = marginals(μ_fourier_marg)
    for t in 1:T+1
        marg = margs[t]
        marg_fourier = margs_fourier[t]
        ind = argmax(abs.(marg))
        push!(er, abs(marg_fourier[ind]-marg[ind])/abs(marg[ind]))
        push!(ptr, (e, t))
    end
end

display(maximum(er))
display(ptr[argmax(er)])

0.042653831618361955

(Indexed Edge 5 => 8 with index 16, 3)

In [313]:
node = 3
time = 3

ed = inedges(bp.g, node) |> first
@show ed
μ = bp.μ[idx(ed)]
μ_marg = marginalize(μ,1)
marg = marginals(μ_marg)[time]

ed_fourier = inedges(bp_fourier.g, node) |> first
@show ed_fourier
μ_fourier = bp_fourier.μ[idx(ed_fourier)]
μ_fourier_marg = marginalize(μ_fourier,1)
marg_fourier = marginals(μ_fourier_marg)[time]

display(marg)
display(marg_fourier);

2-element Vector{Float64}:
 0.2589935066133612
 0.7410064933866389

2-element Vector{Float64}:
 0.27717491737290945
 0.7228250826270906

ed = Indexed Edge 2 => 3 with index 4
ed_fourier = Indexed Edge 2 => 3 with index 4


In [314]:
node = 1
time = 3

edd = inedges(bp.g, node)
for ed in edd
    @show ed
    μ = bp.μ[idx(ed)]
    μ_marg = marginalize(μ,1)
    marg = marginals(μ_marg)[time]

    μ_fourier = bp_fourier.μ[idx(ed_fourier)]
    μ_fourier_marg = marginalize(μ_fourier,1)
    marg_fourier = marginals(μ_fourier_marg)[time]

    display(marg)
    display(marg_fourier)
end

2-element Vector{Float64}:
 0.00010539877535425973
 0.9998946012246457

2-element Vector{Float64}:
 0.27717491737290945
 0.7228250826270906

2-element Vector{Float64}:
 0.009861877518778988
 0.990138122481221

2-element Vector{Float64}:
 0.27717491737290945
 0.7228250826270906

2-element Vector{Float64}:
 0.06098540327776541
 0.9390145967222345

2-element Vector{Float64}:
 0.27717491737290945
 0.7228250826270906

ed = Indexed Edge 7 => 1 with index 21
ed = Indexed Edge 8 => 1 with index 28
ed = Indexed Edge 10 => 1 with index 34


In [315]:
for ed in edges(bp.g)
    display(ed)

    μ = bp.μ[idx(ed)]
    μ_marg = marginalize(μ,1)
    μ_fourier = bp_fourier.μ[idx(ed)]
    μ_fourier_marg = marginalize(μ_fourier,1)

    for time in 1:T+1
        marg = marginals(μ_marg)[time]
        marg_fourier = marginals(μ_fourier_marg)[time]
        display("time = $time")
        display(marg)
        display(marg_fourier)
    end
end

Indexed Edge 1 => 7 with index 1

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 3.225660680111042e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.06083766994185397
 0.9391623300581461

2-element Vector{Float64}:
 0.08585746889134827
 0.9141425311086517

"time = 3"

2-element Vector{Float64}:
 0.06207044883195852
 0.9379295511680416

2-element Vector{Float64}:
 0.08768543120280964
 0.9123145687971903

"time = 4"

2-element Vector{Float64}:
 0.06574101446235268
 0.9342589855376473

2-element Vector{Float64}:
 0.09496978089994831
 0.9050302191000517

"time = 5"

2-element Vector{Float64}:
 0.06583881887076219
 0.9341611811292377

2-element Vector{Float64}:
 0.09562153808498093
 0.9043784619150191

Indexed Edge 1 => 8 with index 2

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 3.057088346268478e-20
 1.0

"time = 2"

2-element Vector{Float64}:
 0.060837781716828174
 0.9391622182831718

2-element Vector{Float64}:
 0.08585865534953471
 0.9141413446504653

"time = 3"

2-element Vector{Float64}:
 0.06192401648588061
 0.9380759835141194

2-element Vector{Float64}:
 0.08738737723194008
 0.9126126227680599

"time = 4"

2-element Vector{Float64}:
 0.0650726639239741
 0.9349273360760258

2-element Vector{Float64}:
 0.09329543829201156
 0.9067045617079884

"time = 5"

2-element Vector{Float64}:
 0.06514169553161642
 0.9348583044683836

2-element Vector{Float64}:
 0.09370891848672636
 0.9062910815132736

Indexed Edge 1 => 10 with index 3

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 7.447811328304292e-21
 1.0

"time = 2"

2-element Vector{Float64}:
 0.060837682823787285
 0.9391623171762127

2-element Vector{Float64}:
 0.08411085017590834
 0.9158891498240916

"time = 3"

2-element Vector{Float64}:
 0.06098540708266666
 0.9390145929173334

2-element Vector{Float64}:
 0.08921653945141554
 0.9107834605485844

"time = 4"

2-element Vector{Float64}:
 0.06152057219479295
 0.9384794278052071

2-element Vector{Float64}:
 0.08587036521291716
 0.9141296347870829

"time = 5"

2-element Vector{Float64}:
 0.06153514644517124
 0.9384648535548288

2-element Vector{Float64}:
 0.08650776027891777
 0.9134922397210822

Indexed Edge 2 => 3 with index 4

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -7.094917252673675e-63
  1.0

"time = 2"

2-element Vector{Float64}:
 0.25899313840412996
 0.74100686159587

2-element Vector{Float64}:
 0.2771706204517913
 0.7228293795482087

"time = 3"

2-element Vector{Float64}:
 0.2589935066133612
 0.7410064933866389

2-element Vector{Float64}:
 0.27717491737290945
 0.7228250826270906

"time = 4"

2-element Vector{Float64}:
 0.2590097953756622
 0.7409902046243378

2-element Vector{Float64}:
 0.277303459246404
 0.722696540753596

"time = 5"

2-element Vector{Float64}:
 0.259010692662427
 0.7409893073375728

2-element Vector{Float64}:
 0.27732742301594715
 0.7226725769840529

Indexed Edge 2 => 7 with index 5

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 1.7747383766198175e-17
 1.0

"time = 2"

2-element Vector{Float64}:
 0.2589934037974829
 0.7410065962025172

2-element Vector{Float64}:
 0.2771718324180647
 0.7228281675819354

"time = 3"

2-element Vector{Float64}:
 0.25901500158610596
 0.740984998413894

2-element Vector{Float64}:
 0.2772378072279984
 0.7227621927720016

"time = 4"

2-element Vector{Float64}:
 0.25964549554967375
 0.7403545044503261

2-element Vector{Float64}:
 0.27885642236431013
 0.7211435776356898

"time = 5"

2-element Vector{Float64}:
 0.25965520940461206
 0.7403447905953879

2-element Vector{Float64}:
 0.27888882929351516
 0.7211111707064848

Indexed Edge 3 => 2 with index 6

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -3.1898578989011203e-19
  1.0

"time = 2"

2-element Vector{Float64}:
 0.0012598260564228535
 0.9987401739435772

2-element Vector{Float64}:
 0.00420976220905842
 0.9957902377909416

"time = 3"

2-element Vector{Float64}:
 0.0025182338837483505
 0.9974817661162517

2-element Vector{Float64}:
 0.006607746597108025
 0.993392253402892

"time = 4"

2-element Vector{Float64}:
 0.0026284311958785513
 0.9973715688041215

2-element Vector{Float64}:
 0.007124946285071183
 0.9928750537149288

"time = 5"

2-element Vector{Float64}:
 0.0027026638057763303
 0.9972973361942237

2-element Vector{Float64}:
 0.007359286943155791
 0.9926407130568442

Indexed Edge 3 => 4 with index 7

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 1.5929449200736758e-19
 1.0

"time = 2"

2-element Vector{Float64}:
 0.00125917790638117
 0.9987408220936188

2-element Vector{Float64}:
 0.004205551287401096
 0.9957944487125989

"time = 3"

2-element Vector{Float64}:
 0.0035497571255310298
 0.9964502428744689

2-element Vector{Float64}:
 0.008401170504235634
 0.9915988294957644

"time = 4"

2-element Vector{Float64}:
 0.003757850354102058
 0.996242149645898

2-element Vector{Float64}:
 0.009260470712946807
 0.9907395292870532

"time = 5"

2-element Vector{Float64}:
 0.0041289551191512315
 0.9958710448808488

2-element Vector{Float64}:
 0.010124277240486724
 0.9898757227595133

Indexed Edge 3 => 6 with index 8

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -4.779908760820071e-19
  1.0

"time = 2"

2-element Vector{Float64}:
 0.0012599392353870383
 0.998740060764613

2-element Vector{Float64}:
 0.004201330640360699
 0.9957986693596393

"time = 3"

2-element Vector{Float64}:
 0.003707012185728456
 0.9962929878142716

2-element Vector{Float64}:
 0.00873178557593767
 0.9912682144240623

"time = 4"

2-element Vector{Float64}:
 0.003975957871168022
 0.996024042128832

2-element Vector{Float64}:
 0.00980804224806848
 0.9901919577519315

"time = 5"

2-element Vector{Float64}:
 0.0044848788668937194
 0.9955151211331063

2-element Vector{Float64}:
 0.010994631775603423
 0.9890053682243967

Indexed Edge 3 => 7 with index 9

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -1.696432535954887e-22
  1.0

"time = 2"

2-element Vector{Float64}:
 0.0012600913629330051
 0.998739908637067

2-element Vector{Float64}:
 0.004208639558268056
 0.995791360441732

"time = 3"

2-element Vector{Float64}:
 0.0037319840621950337
 0.996268015937805

2-element Vector{Float64}:
 0.008819247440821777
 0.9911807525591783

"time = 4"

2-element Vector{Float64}:
 0.004016694578359146
 0.9959833054216408

2-element Vector{Float64}:
 0.009972090610113678
 0.9900279093898863

"time = 5"

2-element Vector{Float64}:
 0.004554337801501265
 0.9954456621984987

2-element Vector{Float64}:
 0.011270720888824675
 0.9887292791111753

Indexed Edge 3 => 9 with index 10

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -4.620716853136721e-19
  1.0

"time = 2"

2-element Vector{Float64}:
 0.0012598297155029185
 0.9987401702844971

2-element Vector{Float64}:
 0.004063748280602176
 0.9959362517193978

"time = 3"

2-element Vector{Float64}:
 0.0025182441246000605
 0.9974817558753999

2-element Vector{Float64}:
 0.013515119229071866
 0.9864848807709282

"time = 4"

2-element Vector{Float64}:
 0.0026284348509873355
 0.9973715651490126

2-element Vector{Float64}:
 0.007025636331818204
 0.9929743636681818

"time = 5"

2-element Vector{Float64}:
 0.0027025724724478134
 0.9972974275275522

2-element Vector{Float64}:
 0.00822193734398208
 0.9917780626560179

Indexed Edge 4 => 3 with index 11

"time = 1"

2-element Vector{Float64}:
 -9.225503453788234e-19
  1.0

2-element Vector{Float64}:
 -3.206748465208109e-18
  1.0

"time = 2"

2-element Vector{Float64}:
 0.060837611324941004
 0.939162388675059

2-element Vector{Float64}:
 0.0858569159071825
 0.9141430840928175

"time = 3"

2-element Vector{Float64}:
 0.06207042598744699
 0.9379295740125531

2-element Vector{Float64}:
 0.08770074573442442
 0.9122992542655756

"time = 4"

2-element Vector{Float64}:
 0.06574188923567158
 0.9342581107643284

2-element Vector{Float64}:
 0.09504745056872875
 0.9049525494312712

"time = 5"

2-element Vector{Float64}:
 0.06584272097144438
 0.9341572790285556

2-element Vector{Float64}:
 0.09527078989467752
 0.9047292101053225

Indexed Edge 4 => 5 with index 12

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 5.038230889265386e-21
 1.0

"time = 2"

2-element Vector{Float64}:
 0.06083754798297038
 0.9391624520170296

2-element Vector{Float64}:
 0.0858571444765157
 0.9141428555234843

"time = 3"

2-element Vector{Float64}:
 0.06100493094225157
 0.9389950690577484

2-element Vector{Float64}:
 0.08621731367163285
 0.9137826863283671

"time = 4"

2-element Vector{Float64}:
 0.061770070720260625
 0.9382299292797394

2-element Vector{Float64}:
 0.08830714974847062
 0.9116928502515294

"time = 5"

2-element Vector{Float64}:
 0.061791715864382514
 0.9382082841356175

2-element Vector{Float64}:
 0.08836882377617822
 0.9116311762238218

Indexed Edge 4 => 6 with index 13

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 3.125191995773907e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.06083746360096613
 0.9391625363990338

2-element Vector{Float64}:
 0.08410785812609947
 0.9158921418739006

"time = 3"

2-element Vector{Float64}:
 0.06194327163724297
 0.9380567283627571

2-element Vector{Float64}:
 0.08920643612600863
 0.9107935638739914

"time = 4"

2-element Vector{Float64}:
 0.06532102262236338
 0.9346789773776367

2-element Vector{Float64}:
 0.09216969768447589
 0.9078303023155241

"time = 5"

2-element Vector{Float64}:
 0.06539715266321766
 0.9346028473367823

2-element Vector{Float64}:
 0.09268097809137472
 0.9073190219086252

Indexed Edge 5 => 4 with index 14

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 6.389295789943657e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.06083768286936982
 0.9391623171306301

2-element Vector{Float64}:
 0.08585856417548042
 0.9141414358245196

"time = 3"

2-element Vector{Float64}:
 0.060985407097198914
 0.9390145929028011

2-element Vector{Float64}:
 0.08615806812489633
 0.9138419318751037

"time = 4"

2-element Vector{Float64}:
 0.06152057261377059
 0.9384794273862294

2-element Vector{Float64}:
 0.08763127388232232
 0.9123687261176777

"time = 5"

2-element Vector{Float64}:
 0.06153514707458637
 0.9384648529254136

2-element Vector{Float64}:
 0.0876806212482152
 0.9123193787517848

Indexed Edge 5 => 7 with index 15

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -6.4905513294053955e-18
  1.0

"time = 2"

2-element Vector{Float64}:
 0.0608376597474927
 0.9391623402525072

2-element Vector{Float64}:
 0.08585719434345125
 0.9141428056565487

"time = 3"

2-element Vector{Float64}:
 0.06207047852883117
 0.9379295214711689

2-element Vector{Float64}:
 0.08770124540647853
 0.9122987545935215

"time = 4"

2-element Vector{Float64}:
 0.06574405335119599
 0.934255946648804

2-element Vector{Float64}:
 0.09505792817710965
 0.9049420718228904

"time = 5"

2-element Vector{Float64}:
 0.06585318107039509
 0.9341468189296049

2-element Vector{Float64}:
 0.09529665146160296
 0.9047033485383971

Indexed Edge 5 => 8 with index 16

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -6.293505905734205e-18
  1.0

"time = 2"

2-element Vector{Float64}:
 0.06083777821610586
 0.9391622217838942

2-element Vector{Float64}:
 0.08411066911154753
 0.9158893308884525

"time = 3"

2-element Vector{Float64}:
 0.061924014973419275
 0.9380759850265807

2-element Vector{Float64}:
 0.10193655008397202
 0.8980634499160279

"time = 4"

2-element Vector{Float64}:
 0.06507570902531573
 0.9349242909746843

2-element Vector{Float64}:
 0.09151753625240472
 0.9084824637475953

"time = 5"

2-element Vector{Float64}:
 0.06515636500390964
 0.9348436349960904

2-element Vector{Float64}:
 0.09319480666836814
 0.9068051933316319

Indexed Edge 6 => 3 with index 17

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 2.1703718965903596e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.009159975162316307
 0.9908400248376836

2-element Vector{Float64}:
 0.019064324673771185
 0.9809356753262288

"time = 3"

2-element Vector{Float64}:
 0.010476179609153652
 0.9895238203908464

2-element Vector{Float64}:
 0.02124520582649078
 0.9787547941735092

"time = 4"

2-element Vector{Float64}:
 0.011277464805055214
 0.9887225351949448

2-element Vector{Float64}:
 0.02386677616487278
 0.9761332238351272

"time = 5"

2-element Vector{Float64}:
 0.011353883575010755
 0.9886461164249892

2-element Vector{Float64}:
 0.023749798829391034
 0.9762502011706089

Indexed Edge 6 => 4 with index 18

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -4.2222542415072536e-22
  1.0

"time = 2"

2-element Vector{Float64}:
 0.00916030922569415
 0.9908396907743058

2-element Vector{Float64}:
 0.01906626208393936
 0.9809337379160606

"time = 3"

2-element Vector{Float64}:
 0.009872730994019184
 0.9901272690059809

2-element Vector{Float64}:
 0.020292019964955346
 0.9797079800350447

"time = 4"

2-element Vector{Float64}:
 0.010343148304225256
 0.9896568516957748

2-element Vector{Float64}:
 0.021699407528592896
 0.9783005924714071

"time = 5"

2-element Vector{Float64}:
 0.010388204921685979
 0.989611795078314

2-element Vector{Float64}:
 0.021859347392195368
 0.9781406526078047

Indexed Edge 6 => 8 with index 19

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 3.7426844574482164e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.009159924379888914
 0.990840075620111

2-element Vector{Float64}:
 0.019064516734197443
 0.9809354832658026

"time = 3"

2-element Vector{Float64}:
 0.01040419461849917
 0.9895958053815008

2-element Vector{Float64}:
 0.021090745105468288
 0.9789092548945317

"time = 4"

2-element Vector{Float64}:
 0.011181688242174132
 0.9888183117578259

2-element Vector{Float64}:
 0.023592189342910266
 0.9764078106570898

"time = 5"

2-element Vector{Float64}:
 0.01125335473855652
 0.9887466452614435

2-element Vector{Float64}:
 0.023407891222671763
 0.9765921087773282

Indexed Edge 6 => 10 with index 20

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 1.4065532571353569e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.009160289937849177
 0.9908397100621508

2-element Vector{Float64}:
 0.018531757806869994
 0.98146824219313

"time = 3"

2-element Vector{Float64}:
 0.009872730987182174
 0.9901272690128178

2-element Vector{Float64}:
 0.04430662444917693
 0.955693375550823

"time = 4"

2-element Vector{Float64}:
 0.010344487154029965
 0.9896555128459701

2-element Vector{Float64}:
 0.021428686459845442
 0.9785713135401546

"time = 5"

2-element Vector{Float64}:
 0.010394077339922186
 0.9896059226600777

2-element Vector{Float64}:
 0.024332342951022885
 0.9756676570489772

Indexed Edge 7 => 1 with index 21

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 7.676362529080415e-25
 1.0

"time = 2"

2-element Vector{Float64}:
 2.3162397731951895e-5
 0.9999768376022681

2-element Vector{Float64}:
 0.00027490347745489654
 0.999725096522545

"time = 3"

2-element Vector{Float64}:
 0.00010539877535425973
 0.9998946012246457

2-element Vector{Float64}:
 0.0006937102509139826
 0.999306289749086

"time = 4"

2-element Vector{Float64}:
 0.00011028765604319086
 0.9998897123439567

2-element Vector{Float64}:
 0.0009044744245651715
 0.9990955255754348

"time = 5"

2-element Vector{Float64}:
 0.00026775626117329557
 0.9997322437388267

2-element Vector{Float64}:
 0.001551611237003361
 0.9984483887629967

Indexed Edge 7 => 2 with index 22

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -2.4719469274575435e-17
  1.0

"time = 2"

2-element Vector{Float64}:
 2.3163972594563373e-5
 0.9999768360274054

2-element Vector{Float64}:
 0.00027494765870096974
 0.999725052341299

"time = 3"

2-element Vector{Float64}:
 6.4602767843754e-5
 0.9999353972321563

2-element Vector{Float64}:
 0.0005246177893661755
 0.9994753822106338

"time = 4"

2-element Vector{Float64}:
 6.857007314444287e-5
 0.9999314299268556

2-element Vector{Float64}:
 0.0006967480425750769
 0.9993032519574249

"time = 5"

2-element Vector{Float64}:
 0.00010022382481237588
 0.9998997761751877

2-element Vector{Float64}:
 0.0009199878070931936
 0.9990800121929069

Indexed Edge 7 => 3 with index 23

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 5.031959328485962e-25
 1.0

"time = 2"

2-element Vector{Float64}:
 2.3177562042301644e-5
 0.9999768224379577

2-element Vector{Float64}:
 0.00027778847811440696
 0.9997222115218857

"time = 3"

2-element Vector{Float64}:
 0.00011467812709140194
 0.9998853218729086

2-element Vector{Float64}:
 0.0007407624940531783
 0.9992592375059468

"time = 4"

2-element Vector{Float64}:
 0.00012096071774865669
 0.9998790392822514

2-element Vector{Float64}:
 0.0009710447303624337
 0.9990289552696375

"time = 5"

2-element Vector{Float64}:
 0.00036844428966355594
 0.9996315557103365

2-element Vector{Float64}:
 0.0019430658662184276
 0.9980569341337816

Indexed Edge 7 => 5 with index 24

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 1.049459283185447e-20
 1.0

"time = 2"

2-element Vector{Float64}:
 2.3164952308112776e-5
 0.9999768350476919

2-element Vector{Float64}:
 0.0002772692955994227
 0.9997227307044005

"time = 3"

2-element Vector{Float64}:
 0.00010540499879037267
 0.9998945950012096

2-element Vector{Float64}:
 0.0006962646560803955
 0.9993037353439197

"time = 4"

2-element Vector{Float64}:
 0.00011029739646932482
 0.9998897026035306

2-element Vector{Float64}:
 0.0009072072650616118
 0.9990927927349385

"time = 5"

2-element Vector{Float64}:
 0.00026636481576135576
 0.9997336351842386

2-element Vector{Float64}:
 0.001528276165498686
 0.9984717238345013

Indexed Edge 7 => 8 with index 25

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -2.1017557390102574e-20
  1.0

"time = 2"

2-element Vector{Float64}:
 2.317849293045837e-5
 0.9999768215070696

2-element Vector{Float64}:
 0.0002775771885535111
 0.9997224228114464

"time = 3"

2-element Vector{Float64}:
 0.0001135317337033288
 0.9998864682662967

2-element Vector{Float64}:
 0.0007334867952256865
 0.9992665132047743

"time = 4"

2-element Vector{Float64}:
 0.00011991995076888189
 0.9998800800492311

2-element Vector{Float64}:
 0.0008654647778287022
 0.9991345352221713

"time = 5"

2-element Vector{Float64}:
 0.00035704962600787533
 0.9996429503739922

2-element Vector{Float64}:
 0.0018521868294993748
 0.9981478131705006

Indexed Edge 7 => 9 with index 26

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 4.313754995477348e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 2.3164138685481245e-5
 0.9999768358613146

2-element Vector{Float64}:
 0.00027542087433606824
 0.9997245791256639

"time = 3"

2-element Vector{Float64}:
 6.460282516064553e-5
 0.9999353971748394

2-element Vector{Float64}:
 0.000525359471772434
 0.9994746405282275

"time = 4"

2-element Vector{Float64}:
 6.857038705612898e-5
 0.9999314296129439

2-element Vector{Float64}:
 0.0006911174252670666
 0.9993088825747329

"time = 5"

2-element Vector{Float64}:
 0.00010048393257730106
 0.9998995160674227

2-element Vector{Float64}:
 0.0007601604249815211
 0.9992398395750185

Indexed Edge 7 => 10 with index 27

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -2.993219604553117e-20
  1.0

"time = 2"

2-element Vector{Float64}:
 2.3162563316702678e-5
 0.9999768374366833

2-element Vector{Float64}:
 0.0002634956483170375
 0.9997365043516829

"time = 3"

2-element Vector{Float64}:
 0.00010539884339300138
 0.999894601156607

2-element Vector{Float64}:
 0.0007048575152962851
 0.9992951424847037

"time = 4"

2-element Vector{Float64}:
 0.00011028810211000524
 0.99988971189789

2-element Vector{Float64}:
 0.0008127161501911558
 0.9991872838498088

"time = 5"

2-element Vector{Float64}:
 0.0002680154693586984
 0.9997319845306414

2-element Vector{Float64}:
 0.0015140633343551082
 0.9984859366656449

Indexed Edge 8 => 1 with index 28

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -1.822192787497769e-17
  1.0

"time = 2"

2-element Vector{Float64}:
 0.009160525392745122
 0.9908394746072549

2-element Vector{Float64}:
 0.01906842169899923
 0.9809315783010008

"time = 3"

2-element Vector{Float64}:
 0.009861877518778988
 0.990138122481221

2-element Vector{Float64}:
 0.020263901142208027
 0.979736098857792

"time = 4"

2-element Vector{Float64}:
 0.010280635120947873
 0.9897193648790521

2-element Vector{Float64}:
 0.02291955800781408
 0.9770804419921859

"time = 5"

2-element Vector{Float64}:
 0.010326231760097027
 0.9896737682399029

2-element Vector{Float64}:
 0.021639949974675537
 0.9783600500253244

Indexed Edge 8 => 5 with index 29

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 7.205487153095036e-19
 1.0

"time = 2"

2-element Vector{Float64}:
 0.009160525684992352
 0.9908394743150076

2-element Vector{Float64}:
 0.019068983025818075
 0.980931016974182

"time = 3"

2-element Vector{Float64}:
 0.009861877558433693
 0.9901381224415663

2-element Vector{Float64}:
 0.02028679466454334
 0.9797132053354567

"time = 4"

2-element Vector{Float64}:
 0.010280634683432061
 0.9897193653165679

2-element Vector{Float64}:
 0.021566724973933988
 0.978433275026066

"time = 5"

2-element Vector{Float64}:
 0.010326068969011502
 0.9896739310309884

2-element Vector{Float64}:
 0.021679265030653653
 0.9783207349693464

Indexed Edge 8 => 6 with index 30

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 1.4451035012645623e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.00916029287303432
 0.9908397071269657

2-element Vector{Float64}:
 0.019067733540212167
 0.9809322664597878

"time = 3"

2-element Vector{Float64}:
 0.010393573484722158
 0.9896064265152777

2-element Vector{Float64}:
 0.021084382710407138
 0.9789156172895929

"time = 4"

2-element Vector{Float64}:
 0.011116460983705993
 0.9888835390162941

2-element Vector{Float64}:
 0.024541853710319132
 0.9754581462896809

"time = 5"

2-element Vector{Float64}:
 0.011186017350133465
 0.9888139826498665

2-element Vector{Float64}:
 0.02327711492542323
 0.9767228850745767

Indexed Edge 8 => 7 with index 31

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -1.5472414066424986e-21
  1.0

"time = 2"

2-element Vector{Float64}:
 0.00915999213249782
 0.9908400078675021

2-element Vector{Float64}:
 0.018530146602522096
 0.9814698533974778

"time = 3"

2-element Vector{Float64}:
 0.010476241316729957
 0.98952375868327

2-element Vector{Float64}:
 0.020715174156603677
 0.9792848258433963

"time = 4"

2-element Vector{Float64}:
 0.011276391511185136
 0.9887236084888149

2-element Vector{Float64}:
 0.02434455183235421
 0.9756554481676458

"time = 5"

2-element Vector{Float64}:
 0.011350923367393354
 0.9886490766326066

2-element Vector{Float64}:
 0.023096983657156456
 0.9769030163428435

Indexed Edge 9 => 3 with index 32

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 1.6314531267231299e-16
 0.9999999999999999

"time = 2"

2-element Vector{Float64}:
 0.2589931384707354
 0.7410068615292644

2-element Vector{Float64}:
 0.27717062219818484
 0.7228293778018152

"time = 3"

2-element Vector{Float64}:
 0.2589935066157578
 0.7410064933842423

2-element Vector{Float64}:
 0.2771879326828271
 0.7228120673171728

"time = 4"

2-element Vector{Float64}:
 0.2590097954962851
 0.740990204503715

2-element Vector{Float64}:
 0.27730362835008004
 0.72269637164992

"time = 5"

2-element Vector{Float64}:
 0.25901069273120203
 0.740989307268798

2-element Vector{Float64}:
 0.2773427113173555
 0.7226572886826444

Indexed Edge 9 => 7 with index 33

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 1.388555256895778e-16
 0.9999999999999999

"time = 2"

2-element Vector{Float64}:
 0.25899340696281653
 0.7410065930371835

2-element Vector{Float64}:
 0.27717441574172746
 0.7228255842582726

"time = 3"

2-element Vector{Float64}:
 0.25901500162594954
 0.7409849983740504

2-element Vector{Float64}:
 0.2788190832402558
 0.7211809167597443

"time = 4"

2-element Vector{Float64}:
 0.2596454982252768
 0.7403545017747233

2-element Vector{Float64}:
 0.28080821080427204
 0.7191917891957279

"time = 5"

2-element Vector{Float64}:
 0.25965520463614117
 0.7403447953638589

2-element Vector{Float64}:
 0.2791013485691865
 0.7208986514308134

Indexed Edge 10 => 1 with index 34

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -7.507267912087467e-21
  1.0

"time = 2"

2-element Vector{Float64}:
 0.06083764018194222
 0.9391623598180577

2-element Vector{Float64}:
 0.08582689369329274
 0.9141731063067072

"time = 3"

2-element Vector{Float64}:
 0.06098540327776541
 0.9390145967222345

2-element Vector{Float64}:
 0.08615303200679593
 0.9138469679932041

"time = 4"

2-element Vector{Float64}:
 0.06152146663938331
 0.9384785333606167

2-element Vector{Float64}:
 0.09051743634948305
 0.909482563650517

"time = 5"

2-element Vector{Float64}:
 0.06153927242254429
 0.9384607275774557

2-element Vector{Float64}:
 0.08769164565405167
 0.9123083543459484

Indexed Edge 10 => 6 with index 35

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 3.2202000505418995e-18
 1.0

"time = 2"

2-element Vector{Float64}:
 0.06083778175345713
 0.9391622182465429

2-element Vector{Float64}:
 0.08585850413805718
 0.9141414958619428

"time = 3"

2-element Vector{Float64}:
 0.06192401729642479
 0.9380759827035752

2-element Vector{Float64}:
 0.0873733604068151
 0.9126266395931848

"time = 4"

2-element Vector{Float64}:
 0.06507266455152638
 0.9349273354484736

2-element Vector{Float64}:
 0.09405703594789724
 0.9059429640521028

"time = 5"

2-element Vector{Float64}:
 0.06514162991177719
 0.9348583700882228

2-element Vector{Float64}:
 0.09338574256456321
 0.9066142574354368

Indexed Edge 10 => 7 with index 36

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{Float64}:
 -6.3338471847078724e-18
  1.0

"time = 2"

2-element Vector{Float64}:
 0.06083760944245538
 0.9391623905575447

2-element Vector{Float64}:
 0.08407645783111033
 0.9159235421688897

"time = 3"

2-element Vector{Float64}:
 0.06207042556951977
 0.9379295744304802

2-element Vector{Float64}:
 0.08837994143920297
 0.9116200585607971

"time = 4"

2-element Vector{Float64}:
 0.06574188900317428
 0.9342581109968257

2-element Vector{Float64}:
 0.09662719298994885
 0.9033728070100512

"time = 5"

2-element Vector{Float64}:
 0.06584282626019923
 0.9341571737398007

2-element Vector{Float64}:
 0.09346591567053807
 0.9065340843294619