In [318]:
using Pkg
Pkg.activate(".")

  Activating project at `~/Desktop/Continuous MPS/MatrixProductBP.jl`


In [319]:
using Revise
using MatrixProductBP, MatrixProductBP.Models
using Graphs, IndexedGraphs, Statistics, Random, LinearAlgebra, TensorTrains, SparseArrays
import ProgressMeter; ProgressMeter.ijulia_behavior(:clear)
using TensorTrains: summary_compact
using SparseArrays
using JLD2
include("bp_fourier.jl");

In [320]:
seed = 4
rng = MersenneTwister(seed)

T = 10
# N = 3
# A = [0 1 1; 
#      1 0 0;
#      1 0 0;]
# N = 4
# A = [0 1 0 0; 
#      1 0 1 0; 
#      0 1 0 1; 
#      0 0 1 0]
# N = 7
# A = [0 1 0 0 0 0 0; 
#      1 0 1 0 0 0 0; 
#      0 1 0 1 0 0 0;
#      0 0 1 0 1 0 0;
#      0 0 0 1 0 1 0;
#      0 0 0 0 1 0 1;
#      0 0 0 0 0 1 0]
# N = 4
# A = [0 1 1 1;
#      1 0 0 1;
#      1 0 0 1;
#      1 1 1 0]
# !!! Here the calculations are wrong for edge 1->2 !!!
# N = 5
# A = [0 1 1 1 1; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0]
# N = 6
# A = [0 1 1 1 0 0; 
#      1 0 0 0 1 0; 
#      1 0 0 0 0 1; 
#      1 0 0 0 0 0; 
#      0 1 0 0 0 0; 
#      0 0 1 0 0 0]
# N = 7
# A = [0 1 1 1 1 0 1;
#      1 0 0 0 1 0 0; 
#      1 0 0 0 0 1 0; 
#      1 0 0 0 0 0 0; 
#      1 1 0 0 0 0 0; 
#      0 0 1 0 0 0 0; 
#      1 0 0 0 0 0 0]
N = 8
A = [0 1 1 1 0 0 1 0;
     1 0 0 0 1 0 0 1; 
     1 0 0 0 0 1 0 0; 
     1 0 0 0 0 0 0 0; 
     0 1 0 0 0 0 0 0; 
     0 0 1 0 0 0 0 0; 
     1 0 0 0 0 0 0 0;
     0 1 0 0 0 0 0 0]
# N = 10
# A = [0 1 1 1 1 1 1 1 1 1;
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0 0 0]

g = IndexedBiDiGraph(A)

# N = 20
# c = 3
# gg = erdos_renyi(N, c/N; seed)
# g = IndexedBiDiGraph(gg)
# A = zeros(Int,N,N)
# for i in CartesianIndices(A)
#      if !iszero(g.A[i])
#          A[i] = 1
#      end
# end

β = 1.0
J = 1
h = 0.0
m⁰ = 1.0
K = 100

svd_trunc=TruncBond(4)

A

8×8 Matrix{Int64}:
 0  1  1  1  0  0  1  0
 1  0  0  0  1  0  0  1
 1  0  0  0  0  1  0  0
 1  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0
 0  0  1  0  0  0  0  0
 1  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0

In [321]:
w = [fill(IntegerGlauberFactor([J*A[j,i] for j in inneighbors(g,i)], h, β), T+1) for i in vertices(g)]
ϕᵢ = [t == 0 ? [(1-m⁰)/2, (1+m⁰)/2] : ones(2) for t in 0:T]
# ϕᵢ = [ones(2) for t in 0:T]
bp = mpbp(g, w, fill(2,N), T; ϕ=fill(ϕᵢ,N))

for μ in bp.μ
    for a in μ
        a.=rand.(rng)
        # a.=1.0
    end
end
# bp_fourier = deepcopy(bp)
iterate!(bp, maxiter=2; svd_trunc)

msg = deepcopy(bp.μ)
# jldsave("messages.jld2"; msg)

bp_fourier = convert_msg_beliefs(ComplexF64, bp)
# iterate_fourier!(bp_fourier,K, maxiter=1, σ=1/100; svd_trunc)
;

Running MPBP: iter 2    Time: 0:00:00

In [322]:
# for (k,ed) in enumerate(edges(bp.g))
#     display(ed)
#     display(bp.μ[idx(ed)][3])
# end

In [323]:
iterate!(bp,maxiter=1; svd_trunc)

(1, CB_BP{ProgressUnknown, MatrixProductBP.var"#162#165"}(ProgressUnknown(false, false, 0, ProgressMeter.ProgressCore(:green, "Running MPBP: iter", 0.1, true, 0, VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}(IOContext(Base.PipeEndpoint(RawFD(25) open, 0 bytes waiting)), VSCodeServer.io_send_callback), false, 1, 1, ReentrantLock(nothing, 0x00000000, 0x00, Base.GenericCondition{Base.Threads.SpinLock}(Base.IntrusiveLinkedList{Task}(nothing, nothing), Base.Threads.SpinLock(0)), (132991630195264, 132991630197056, 132988893233200)), 0, 1, false, false, 1.737732011215156e9, 1.737732011215156e9, 1.737732011215156e9)), [[[2.0, 1.9998330208911554, 1.6254524515156616, 1.9578384244591172, 1.5710399696279016, 1.8937465353992748, 1.474298991815529, 1.8739023194200033, 1.4476364811673537, 1.9142230918470766, 1.4564445395976815], [2.0, 1.9975876955112795, 1.972805274858783, 1.9383417927605053, 1.9514182200857153, 1.889285623536548, 1.9338104786250179, 1.

In [324]:
iterate_fourier!(bp_fourier,K, maxiter=1, σ=1/100; svd_trunc)
;

In [325]:
import MatrixProductBP: marginalize
function marginalize(A::MPEM2{F}, var) where F
    if var==1
        return MPEM1{F}([@tullio b[m, n, xi] := a[m, n, xi, xj] for a in A]; z = A.z)
    elseif var==2
        return MPEM1{F}([@tullio b[m, n, xj] := a[m, n, xi, xj] for a in A]; z = A.z)
    end
end;

In [326]:
er_b = []
ptr = []
for i in vertices(bp.g)
    margs = marginals(bp.b[i])
    margs_fourier = marginals(bp_fourier.b[i])
    for t in 1:T+1
        marg = margs[t]
        marg_fourier = margs_fourier[t]
        ind = argmax(abs.(marg))
        push!(er_b, abs(marg_fourier[ind]-marg[ind]))
        push!(ptr, (i, t))
    end
end

display(maximum(er_b))
display(ptr[argmax(er_b)])

0.005004641418676403

(3, 7)

In [327]:
er_μ = []
ptr = []
for e in edges(bp.g)
    μ_marg = marginalize(bp.μ[idx(e)],1)
    margs = marginals(μ_marg)
    μ_fourier_marg = marginalize(bp_fourier.μ[idx(e)],1)
    margs_fourier = marginals(μ_fourier_marg)
    for t in 1:T+1
        marg = margs[t]
        marg_fourier = margs_fourier[t]
        push!(er_μ, abs(marg_fourier[1]-marg[1]))
        push!(ptr, (e, t))
    end
end

display(maximum(er_μ))
display(ptr[argmax(er_μ)])

0.004508653827397208

(Indexed Edge 2 => 8 with index 7, 8)

In [328]:
er_μ = []
ptr = []
for e in edges(bp.g)
    μ = bp.μ[idx(e)]
    μ_fourier = bp_fourier.μ[idx(e)]
    push!(er_μ, norm2m(μ, μ_fourier)/(norm(μ)*norm(μ_fourier)))
    push!(ptr, (e))
end

display(maximum(abs, er_μ))
display(ptr[argmax(abs.(er_μ))])

0.0007151611962720319

Indexed Edge 2 => 8 with index 7

In [329]:
bp_fourier.μ[1][3]

4×4×2×2 Array{ComplexF64, 4}:
[:, :, 1, 1] =
  -0.0105688-1.92632e-17im  …   -0.344549-0.000487437im
 -0.00989288-0.00148495im       -0.319254-0.0483827im
  2.21328e-5+1.3833e-6im       -0.0495725-0.00316869im
 7.65976e-19+2.10136e-5im      6.59103e-5-0.0465893im

[:, :, 2, 1] =
    -0.41176-3.84312e-16im  …    0.0183599+2.59739e-5im
  0.00175009+0.000262693im       0.0021116+0.000320012im
 0.000853871+5.3367e-5im        -0.0118659-0.00075847im
 2.82383e-20-3.32971e-6im      -5.03324e-7+0.000355779im

[:, :, 1, 2] =
   -0.0122143-2.43149e-17im  …    0.296929+0.000420068im
   -0.0114335-0.00171619im        0.275093+0.0416902im
  -1.43356e-5-8.95973e-7im      -0.0353323-0.00225845im
 -4.04567e-19-1.3606e-5im       4.69779e-5-0.0332067im

[:, :, 2, 2] =
    -0.475815-4.96861e-16im  …   -0.0158378-2.24059e-5im
   0.00202277+0.000303622im     -0.00176282-0.000267155im
 -0.000566144-3.5384e-5im         -0.012543-0.00080175im
 -3.34709e-21+2.20947e-6im      -3.79111e-7+0.000267978im

In [330]:
node = 2
time = 3

ed = inedges(bp.g, node) |> first
@show ed
μ = bp.μ[idx(ed)]
μ_marg = marginalize(μ,1)
marg = marginals(μ_marg)[time]

ed_fourier = inedges(bp_fourier.g, node) |> first
@show ed_fourier
μ_fourier = bp_fourier.μ[idx(ed_fourier)]
μ_fourier_marg = marginalize(μ_fourier,1)
marg_fourier = marginals(μ_fourier_marg)[time]

@show marg
@show marg_fourier;

ed = Indexed Edge 1 => 2 with index 1
ed_fourier = Indexed Edge 1 => 2 with index 1
marg = [0.07451493927100153, 0.9254850607289985]
marg_fourier = ComplexF64[0.07558333135216694 + 4.9973227521452986e-17im, 0.9244166686478331 - 4.9973227521452906e-17im]


In [331]:
node = 1
time = 3

edd = outedges(bp.g, node)
for ed in edd
    display(ed)
    μ = bp.μ[idx(ed)]
    μ_marg = marginalize(μ,1)
    marg = marginals(μ_marg)[time]

    μ_fourier = bp_fourier.μ[idx(ed)]
    μ_fourier_marg = marginalize(μ_fourier,1)
    marg_fourier = marginals(μ_fourier_marg)[time]

    display(marg)
    display(marg_fourier)
end

Indexed Edge 1 => 2 with index 1

2-element Vector{Float64}:
 0.07451493927100153
 0.9254850607289985

2-element Vector{ComplexF64}:
 0.07558333135216694 + 4.9973227521452986e-17im
  0.9244166686478331 - 4.9973227521452906e-17im

Indexed Edge 1 => 3 with index 2

2-element Vector{Float64}:
 0.06136183456388506
 0.9386381654361149

2-element Vector{ComplexF64}:
 0.062255816668674045 + 4.710805099734731e-17im
   0.9377441833313259 - 4.710805099734731e-17im

Indexed Edge 1 => 4 with index 3

2-element Vector{Float64}:
 0.039076283535672364
 0.9609237164643276

2-element Vector{ComplexF64}:
 0.04026274516894552 + 7.546382934540041e-17im
  0.9597372548310547 - 7.546382934540032e-17im

Indexed Edge 1 => 7 with index 4

2-element Vector{Float64}:
 0.039076283535672045
 0.960923716464328

2-element Vector{ComplexF64}:
 0.04026274516894509 + 1.0069737541124327e-16im
   0.959737254831055 - 1.0069737541124325e-16im

In [332]:
for ed in edges(bp.g)
    display(ed)

    μ = bp.μ[idx(ed)]
    μ_marg = marginalize(μ,1)
    μ_fourier = bp_fourier.μ[idx(ed)]
    μ_fourier_marg = marginalize(μ_fourier,1)

    for time in 1:T+1
        marg = marginals(μ_marg)[time]
        marg_fourier = marginals(μ_fourier_marg)[time]
        display("time = $time")
        display(marg)
        display(marg_fourier)
    end
end

Indexed Edge 1 => 2 with index 1

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -4.0832238759116964e-18 - 1.2276614757613498e-18im
                     1.0 + 1.2276614757613612e-18im

"time = 2"

2-element Vector{Float64}:
 0.009239084448886388
 0.9907609155511137

2-element Vector{ComplexF64}:
 0.010342140155047863 + 1.3286313869156863e-16im
   0.9896578598449521 - 1.3286313869156868e-16im

"time = 3"

2-element Vector{Float64}:
 0.07451493927100153
 0.9254850607289985

2-element Vector{ComplexF64}:
 0.07558333135216694 + 4.9973227521452986e-17im
  0.9244166686478331 - 4.9973227521452906e-17im

"time = 4"

2-element Vector{Float64}:
 0.09960263818244272
 0.9003973618175574

2-element Vector{ComplexF64}:
 0.10137624749822685 + 3.3342435884766276e-16im
  0.8986237525017732 - 3.3342435884766276e-16im

"time = 5"

2-element Vector{Float64}:
 0.15054060396478786
 0.8494593960352121

2-element Vector{ComplexF64}:
 0.1521675306676111 - 8.366784539124837e-17im
 0.8478324693323889 + 8.366784539124832e-17im

"time = 6"

2-element Vector{Float64}:
 0.17217528501015758
 0.8278247149898424

2-element Vector{ComplexF64}:
 0.17428455699298973 + 2.0012592783226144e-16im
  0.8257154430070103 - 2.0012592783226136e-16im

"time = 7"

2-element Vector{Float64}:
 0.22263810369676257
 0.7773618963032375

2-element Vector{ComplexF64}:
 0.22452119773880233 + 5.583226583138012e-17im
  0.7754788022611976 - 5.583226583138022e-17im

"time = 8"

2-element Vector{Float64}:
 0.23660260809296052
 0.7633973919070395

2-element Vector{ComplexF64}:
 0.2388189962495934 + 3.6667714310831746e-16im
 0.7611810037504064 - 3.666771431083175e-16im

"time = 9"

2-element Vector{Float64}:
 0.28431330874364835
 0.7156866912563518

2-element Vector{ComplexF64}:
 0.2862363267590228 + 2.2050431469479094e-16im
 0.7137636732409771 - 2.20504314694791e-16im

"time = 10"

2-element Vector{Float64}:
 0.29220370277372365
 0.7077962972262765

2-element Vector{ComplexF64}:
 0.29439016493887715 + 1.7523983387148517e-16im
  0.7056098350611227 - 1.7523983387148517e-16im

"time = 11"

2-element Vector{Float64}:
 0.32737090335957014
 0.6726290966404298

2-element Vector{ComplexF64}:
 0.32926912540403536 + 4.211141887522345e-16im
  0.6707308745959646 - 4.211141887522345e-16im

Indexed Edge 1 => 3 with index 2

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.5424769549604233e-16 - 3.409961701655956e-17im
     0.9999999999999999 + 3.4099617016559546e-17im

"time = 2"

2-element Vector{Float64}:
 0.008847235342268799
 0.9911527646577313

2-element Vector{ComplexF64}:
 0.00995121134947155 + 1.7280474362172072e-16im
  0.9900487886505285 - 1.7280474362172074e-16im

"time = 3"

2-element Vector{Float64}:
 0.06136183456388506
 0.9386381654361149

2-element Vector{ComplexF64}:
 0.062255816668674045 + 4.710805099734731e-17im
   0.9377441833313259 - 4.710805099734731e-17im

"time = 4"

2-element Vector{Float64}:
 0.08548121275174146
 0.9145187872482586

2-element Vector{ComplexF64}:
 0.08746316060199448 + 4.74057263559214e-16im
  0.9125368393980057 - 4.74057263559214e-16im

"time = 5"

2-element Vector{Float64}:
 0.10769386917455727
 0.8923061308254427

2-element Vector{ComplexF64}:
 0.10898359603175169 + 6.053209162372092e-17im
  0.8910164039682483 - 6.053209162372093e-17im

"time = 6"

2-element Vector{Float64}:
 0.14496158747814986
 0.8550384125218501

2-element Vector{ComplexF64}:
 0.14705146220904614 + 2.0847228544172835e-16im
  0.8529485377909538 - 2.0847228544172835e-16im

"time = 7"

2-element Vector{Float64}:
 0.14635215777824065
 0.8536478422217594

2-element Vector{ComplexF64}:
 0.1482415204313548 + 7.42874398251236e-17im
 0.8517584795686451 - 7.42874398251236e-17im

"time = 8"

2-element Vector{Float64}:
 0.1980776833958258
 0.8019223166041742

2-element Vector{ComplexF64}:
 0.20050468338074268 + 2.6220753625771947e-16im
  0.7994953166192573 - 2.6220753625771947e-16im

"time = 9"

2-element Vector{Float64}:
 0.18391336005328865
 0.8160866399467114

2-element Vector{ComplexF64}:
 0.18591635858567984 + 3.0724101838002123e-16im
  0.8140836414143202 - 3.0724101838002123e-16im

"time = 10"

2-element Vector{Float64}:
 0.2439799586194033
 0.7560200413805968

2-element Vector{ComplexF64}:
 0.2463182482196352 + 5.921518572754957e-16im
 0.7536817517803648 - 5.921518572754958e-16im

"time = 11"

2-element Vector{Float64}:
 0.2163075119760998
 0.7836924880239001

2-element Vector{ComplexF64}:
 0.21835749746097716 + 1.033229909712877e-16im
  0.7816425025390229 - 1.0332299097128771e-16im

Indexed Edge 1 => 4 with index 3

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5692234100747627e-16 + 1.1507325585562353e-18im
                     1.0 - 1.1507325585562276e-18im

"time = 2"

2-element Vector{Float64}:
 0.008010128517847114
 0.9919898714821529

2-element Vector{ComplexF64}:
 0.008983462029793037 + 1.1178595618178387e-16im
    0.991016537970207 - 1.1178595618178385e-16im

"time = 3"

2-element Vector{Float64}:
 0.039076283535672364
 0.9609237164643276

2-element Vector{ComplexF64}:
 0.04026274516894552 + 7.546382934540041e-17im
  0.9597372548310547 - 7.546382934540032e-17im

"time = 4"

2-element Vector{Float64}:
 0.0662093107187561
 0.9337906892812439

2-element Vector{ComplexF64}:
 0.0678102689807079 + 1.861878769139586e-16im
 0.9321897310192921 - 1.8618787691395855e-16im

"time = 5"

2-element Vector{Float64}:
 0.07146920924648155
 0.9285307907535184

2-element Vector{ComplexF64}:
 0.0733055210799611 + 1.0440342051114233e-16im
  0.926694478920039 - 1.044034205111423e-16im

"time = 6"

2-element Vector{Float64}:
 0.10468067615844559
 0.8953193238415543

2-element Vector{ComplexF64}:
 0.10577649417956914 + 5.0558240899937955e-18im
  0.8942235058204309 - 5.0558240899938864e-18im

"time = 7"

2-element Vector{Float64}:
 0.09904463310437549
 0.9009553668956245

2-element Vector{ComplexF64}:
 0.10045382020196968 + 3.2778029540873296e-16im
  0.8995461797980303 - 3.2778029540873296e-16im

"time = 8"

2-element Vector{Float64}:
 0.1361870987475524
 0.8638129012524476

2-element Vector{ComplexF64}:
 0.1380590369592107 + 1.174857699975246e-16im
 0.8619409630407893 - 1.174857699975246e-16im

"time = 9"

2-element Vector{Float64}:
 0.11880332848370982
 0.8811966715162901

2-element Vector{ComplexF64}:
 0.12013991650774727 + 6.823847652883953e-16im
  0.8798600834922526 - 6.823847652883953e-16im

"time = 10"

2-element Vector{Float64}:
 0.14584098933891934
 0.8541590106610807

2-element Vector{ComplexF64}:
 0.14728853021074717 - 1.6107531361469653e-16im
  0.8527114697892529 + 1.6107531361469663e-16im

"time = 11"

2-element Vector{Float64}:
 0.11319861752554199
 0.886801382474458

2-element Vector{ComplexF64}:
 0.11608355055145049 + 1.7696059165286948e-16im
  0.8839164494485494 - 1.769605916528695e-16im

Indexed Edge 1 => 7 with index 4

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 3.4234463146294613e-19 + 1.375452441613797e-19im
                    1.0 - 1.3754524416137567e-19im

"time = 2"

2-element Vector{Float64}:
 0.008010128517847895
 0.991989871482152

2-element Vector{ComplexF64}:
 0.008983462029793044 + 1.4566056531683322e-16im
   0.9910165379702068 - 1.4566056531683324e-16im

"time = 3"

2-element Vector{Float64}:
 0.039076283535672045
 0.960923716464328

2-element Vector{ComplexF64}:
 0.04026274516894509 + 1.0069737541124327e-16im
   0.959737254831055 - 1.0069737541124325e-16im

"time = 4"

2-element Vector{Float64}:
 0.06620931071875549
 0.9337906892812445

2-element Vector{ComplexF64}:
 0.06781026898070831 + 1.9548580993524755e-16im
  0.9321897310192917 - 1.9548580993524755e-16im

"time = 5"

2-element Vector{Float64}:
 0.0714692092464808
 0.9285307907535192

2-element Vector{ComplexF64}:
 0.07330552107996095 + 9.008633823157627e-17im
   0.926694478920039 - 9.008633823157631e-17im

"time = 6"

2-element Vector{Float64}:
 0.1046806761584443
 0.8953193238415557

2-element Vector{ComplexF64}:
 0.1057764941795699 + 2.0231623944021463e-16im
   0.89422350582043 - 2.0231623944021465e-16im

"time = 7"

2-element Vector{Float64}:
 0.09904463310437339
 0.9009553668956266

2-element Vector{ComplexF64}:
 0.10045382020196945 + 2.0773974273957373e-16im
  0.8995461797980305 - 2.0773974273957373e-16im

"time = 8"

2-element Vector{Float64}:
 0.13618709874754953
 0.8638129012524505

2-element Vector{ComplexF64}:
 0.13805903695921165 + 2.428358830068016e-16im
  0.8619409630407884 - 2.428358830068016e-16im

"time = 9"

2-element Vector{Float64}:
 0.11880332848370945
 0.8811966715162906

2-element Vector{ComplexF64}:
 0.12013991650774711 + 3.7734816058868256e-16im
   0.879860083492253 - 3.7734816058868256e-16im

"time = 10"

2-element Vector{Float64}:
 0.14584098933891684
 0.8541590106610831

2-element Vector{ComplexF64}:
 0.14728853021074645 + 1.0531382387006789e-16im
  0.8527114697892535 - 1.0531382387006789e-16im

"time = 11"

2-element Vector{Float64}:
 0.11319861752553959
 0.8868013824744604

2-element Vector{ComplexF64}:
 0.11608355055145145 - 4.355477913356819e-17im
  0.8839164494485484 + 4.355477913356817e-17im

Indexed Edge 2 => 1 with index 5

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -2.1913394362568227e-17 + 1.3967977257206538e-17im
                     1.0 - 1.3967977257206507e-17im

"time = 2"

2-element Vector{Float64}:
 0.06083777258937603
 0.9391622274106239

2-element Vector{ComplexF64}:
 0.06293449272693959 - 5.8397045099130395e-18im
  0.9370655072730604 + 5.8397045099130426e-18im

"time = 3"

2-element Vector{Float64}:
 0.16553661408755205
 0.834463385912448

2-element Vector{ComplexF64}:
  0.167133463890995 + 2.595163340460812e-16im
 0.8328665361090051 - 2.5951633404608123e-16im

"time = 4"

2-element Vector{Float64}:
 0.20623262891078017
 0.7937673710892198

2-element Vector{ComplexF64}:
 0.2090310370825834 + 3.159794435648706e-16im
 0.7909689629174166 - 3.1597944356487053e-16im

"time = 5"

2-element Vector{Float64}:
 0.276268486967962
 0.7237315130320379

2-element Vector{ComplexF64}:
 0.2783997382775866 - 6.321623471320922e-16im
 0.7216002617224135 + 6.321623471320922e-16im

"time = 6"

2-element Vector{Float64}:
 0.30349114078980205
 0.696508859210198

2-element Vector{ComplexF64}:
 0.3062923383969004 + 1.6193619664202987e-16im
 0.6937076616030996 - 1.6193619664202992e-16im

"time = 7"

2-element Vector{Float64}:
 0.35034000123197895
 0.6496599987680209

2-element Vector{ComplexF64}:
 0.35247337695922326 - 1.193872318669374e-16im
  0.6475266230407768 + 1.1938723186693738e-16im

"time = 8"

2-element Vector{Float64}:
 0.3685499631735289
 0.631450036826471

2-element Vector{ComplexF64}:
 0.3710424033288022 - 3.233517088158289e-16im
  0.628957596671198 + 3.233517088158289e-16im

"time = 9"

2-element Vector{Float64}:
 0.3998884201527902
 0.6001115798472099

2-element Vector{ComplexF64}:
 0.40178664800911545 + 1.0521033228162366e-16im
  0.5982133519908845 - 1.0521033228162367e-16im

"time = 10"

2-element Vector{Float64}:
 0.4120695512094043
 0.5879304487905956

2-element Vector{ComplexF64}:
 0.4141486629822319 + 5.5481769273796504e-17im
 0.5858513370177681 - 5.5481769273796504e-17im

"time = 11"

2-element Vector{Float64}:
 0.43303268407051515
 0.5669673159294849

2-element Vector{ComplexF64}:
 0.4346161234462802 + 3.4774751491818545e-16im
 0.5653838765537199 - 3.4774751491818545e-16im

Indexed Edge 2 => 5 with index 6

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 4.50283243798992e-17 + 1.4905841773353095e-16im
                  1.0 - 1.490584177335308e-16im

"time = 2"

2-element Vector{Float64}:
 0.05833146858501243
 0.9416685314149876

2-element Vector{ComplexF64}:
 0.060234505249525234 - 2.872766223521306e-16im
   0.9397654947504748 + 2.8727662235213036e-16im

"time = 3"

2-element Vector{Float64}:
 0.09815852675373846
 0.9018414732462615

2-element Vector{ComplexF64}:
 0.09939143890252046 - 7.423661772008158e-17im
  0.9006085610974796 + 7.423661772008141e-17im

"time = 4"

2-element Vector{Float64}:
 0.13830010963451983
 0.8616998903654802

2-element Vector{ComplexF64}:
 0.13848472338225046 + 1.3136489772332744e-16im
  0.8615152766177495 - 1.3136489772332725e-16im

"time = 5"

2-element Vector{Float64}:
 0.13275586090461786
 0.8672441390953821

2-element Vector{ComplexF64}:
 0.133216093734192 - 3.1064647831246054e-17im
 0.866783906265808 + 3.1064647831246103e-17im

"time = 6"

2-element Vector{Float64}:
 0.18413302711788665
 0.8158669728821134

2-element Vector{ComplexF64}:
 0.18215287329064864 + 2.441815897248347e-16im
  0.8178471267093513 - 2.4418158972483463e-16im

"time = 7"

2-element Vector{Float64}:
 0.15061390952047884
 0.8493860904795212

2-element Vector{ComplexF64}:
 0.15023774290204772 - 2.4650375615317553e-16im
  0.8497622570979523 + 2.4650375615317553e-16im

"time = 8"

2-element Vector{Float64}:
 0.2204764256308718
 0.7795235743691281

2-element Vector{ComplexF64}:
 0.22498507945826468 + 2.2216979423786364e-16im
  0.7750149205417353 - 2.221697942378636e-16im

"time = 9"

2-element Vector{Float64}:
 0.1762726411607699
 0.8237273588392302

2-element Vector{ComplexF64}:
 0.17587469189726926 - 1.6756885005883139e-16im
  0.8241253081027308 + 1.6756885005883163e-16im

"time = 10"

2-element Vector{Float64}:
 0.25148106468811976
 0.7485189353118803

2-element Vector{ComplexF64}:
 0.25489574404854093 - 6.973273229144055e-17im
  0.7451042559514591 + 6.973273229144039e-17im

"time = 11"

2-element Vector{Float64}:
 0.20101572202078805
 0.798984277979212

2-element Vector{ComplexF64}:
 0.20286712432051598 - 9.738485609831451e-17im
  0.7971328756794839 + 9.738485609831458e-17im

Indexed Edge 2 => 8 with index 7

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.485169992972573e-16 + 9.016353958475826e-18im
     1.0000000000000002 - 9.016353958475746e-18im

"time = 2"

2-element Vector{Float64}:
 0.0583314685850118
 0.9416685314149882

2-element Vector{ComplexF64}:
 0.06023450524952416 - 2.5555241587377466e-18im
  0.9397654947504759 + 2.5555241587378915e-18im

"time = 3"

2-element Vector{Float64}:
 0.09815852675373815
 0.9018414732462618

2-element Vector{ComplexF64}:
 0.09939143890251897 + 2.1826410201819217e-17im
   0.900608561097481 - 2.1826410201819155e-17im

"time = 4"

2-element Vector{Float64}:
 0.13830010963451994
 0.86169989036548

2-element Vector{ComplexF64}:
 0.1384847233822505 + 1.4286683204535493e-16im
 0.8615152766177495 - 1.4286683204535505e-16im

"time = 5"

2-element Vector{Float64}:
 0.13275586090461755
 0.8672441390953823

2-element Vector{ComplexF64}:
 0.1332160937341919 + 2.429577150962466e-16im
  0.866783906265808 - 2.429577150962466e-16im

"time = 6"

2-element Vector{Float64}:
 0.18413302711788757
 0.8158669728821124

2-element Vector{ComplexF64}:
 0.18215287329065202 + 1.1108326978464203e-16im
  0.8178471267093481 - 1.1108326978464186e-16im

"time = 7"

2-element Vector{Float64}:
 0.15061390952047937
 0.8493860904795206

2-element Vector{ComplexF64}:
 0.15023774290204783 - 5.3335943414257734e-17im
  0.8497622570979522 + 5.3335943414257845e-17im

"time = 8"

2-element Vector{Float64}:
 0.22047642563087172
 0.7795235743691283

2-element Vector{ComplexF64}:
 0.22498507945826893 + 1.398622556124291e-16im
   0.775014920541731 - 1.3986225561242911e-16im

"time = 9"

2-element Vector{Float64}:
 0.17627264116077143
 0.8237273588392285

2-element Vector{ComplexF64}:
 0.17587469189726918 + 1.3755525818313005e-16im
  0.8241253081027308 - 1.3755525818313005e-16im

"time = 10"

2-element Vector{Float64}:
 0.25148106468812104
 0.748518935311879

2-element Vector{ComplexF64}:
 0.25489574404854426 + 2.0311214227471424e-16im
  0.7451042559514558 - 2.031121422747141e-16im

"time = 11"

2-element Vector{Float64}:
 0.20101572202078796
 0.798984277979212

2-element Vector{ComplexF64}:
 0.20286712432051598 - 8.530426482587525e-17im
  0.7971328756794841 + 8.530426482587535e-17im

Indexed Edge 3 => 1 with index 8

"time = 1"

2-element Vector{Float64}:
 6.74099149541921e-17
 1.0

2-element Vector{ComplexF64}:
 -1.9828396360065865e-18 + 1.3183497115417543e-17im
                     1.0 - 1.3183497115417551e-17im

"time = 2"

2-element Vector{Float64}:
 0.2589931049810465
 0.7410068950189534

2-element Vector{ComplexF64}:
 0.2591163975991233 + 4.919423559082001e-18im
 0.7408836024008766 - 4.919423559082053e-18im

"time = 3"

2-element Vector{Float64}:
 0.3164505572085206
 0.6835494427914793

2-element Vector{ComplexF64}:
 0.3165444561459205 + 1.3963934125946782e-17im
 0.6834555438540795 - 1.396393412594698e-17im

"time = 4"

2-element Vector{Float64}:
 0.41152663742073253
 0.5884733625792674

2-element Vector{ComplexF64}:
 0.41161713543203504 + 9.769421233807181e-17im
  0.5883828645679648 - 9.769421233807181e-17im

"time = 5"

2-element Vector{Float64}:
 0.43261920410187465
 0.5673807958981253

2-element Vector{ComplexF64}:
 0.43268812685840785 + 1.236394123661393e-16im
  0.5673118731415921 - 1.236394123661394e-16im

"time = 6"

2-element Vector{Float64}:
 0.4675215271933737
 0.5324784728066264

2-element Vector{ComplexF64}:
 0.46757134702660424 + 2.348721561113678e-16im
  0.5324286529733957 - 2.348721561113677e-16im

"time = 7"

2-element Vector{Float64}:
 0.4752645849161054
 0.5247354150838945

2-element Vector{ComplexF64}:
 0.4753025274099447 + 2.4219744194830085e-16im
 0.5246974725900553 - 2.4219744194830094e-16im

"time = 8"

2-element Vector{Float64}:
 0.48807718882725065
 0.5119228111727493

2-element Vector{ComplexF64}:
 0.48810156766462093 + 1.3711506616516447e-16im
  0.5118984323353791 - 1.3711506616516457e-16im

"time = 9"

2-element Vector{Float64}:
 0.49091965668827015
 0.5090803433117298

2-element Vector{ComplexF64}:
 0.49093822346834004 + 1.383677337865248e-16im
  0.5090617765316598 - 1.383677337865248e-16im

"time = 10"

2-element Vector{Float64}:
 0.4956231493054673
 0.5043768506945329

2-element Vector{ComplexF64}:
 0.4956343332498039 + 1.2113372613311374e-16im
  0.504365666750196 - 1.2113372613311384e-16im

"time = 11"

2-element Vector{Float64}:
 0.49666661608955337
 0.5033333839104467

2-element Vector{ComplexF64}:
 0.4966751337162004 + 1.951455797187242e-16im
 0.5033248662837996 - 1.9514557971872403e-16im

Indexed Edge 3 => 6 with index 9

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.354618315454798e-16 + 6.726915960117579e-18im
                    1.0 - 6.726915960117588e-18im

"time = 2"

2-element Vector{Float64}:
 0.25301696834816617
 0.7469830316518338

2-element Vector{ComplexF64}:
 0.25317931162632945 + 1.617156092118766e-17im
  0.7468206883736705 - 1.617156092118766e-17im

"time = 3"

2-element Vector{Float64}:
 0.25613932746074775
 0.7438606725392524

2-element Vector{ComplexF64}:
 0.25636772916692663 + 3.739099602695221e-17im
  0.7436322708330734 - 3.739099602695221e-17im

"time = 4"

2-element Vector{Float64}:
 0.2690032766630546
 0.7309967233369453

2-element Vector{ComplexF64}:
 0.26945109836510406 - 3.153654981708577e-17im
  0.7305489016348959 + 3.153654981708579e-17im

"time = 5"

2-element Vector{Float64}:
 0.2781085460217899
 0.7218914539782101

2-element Vector{ComplexF64}:
 0.27839572057405554 + 8.79391518776195e-17im
  0.7216042794259445 - 8.793915187761952e-17im

"time = 6"

2-element Vector{Float64}:
 0.285198723849804
 0.7148012761501961

2-element Vector{ComplexF64}:
 0.28565260041577145 + 2.25630830593652e-16im
  0.7143473995842285 - 2.256308305936519e-16im

"time = 7"

2-element Vector{Float64}:
 0.2999970431269781
 0.7000029568730217

2-element Vector{ComplexF64}:
  0.300490449673237 + 4.5525385326295596e-17im
 0.6995095503267631 - 4.5525385326295596e-17im

"time = 8"

2-element Vector{Float64}:
 0.3021488029721725
 0.6978511970278275

2-element Vector{ComplexF64}:
 0.3026272503017571 + 1.0940443130040504e-16im
 0.6973727496982429 - 1.0940443130040508e-16im

"time = 9"

2-element Vector{Float64}:
 0.3206689778463218
 0.6793310221536781

2-element Vector{ComplexF64}:
 0.32112761500163806 + 1.7244807543786355e-16im
  0.6788723849983619 - 1.7244807543786365e-16im

"time = 10"

2-element Vector{Float64}:
 0.31773660480431337
 0.6822633951956866

2-element Vector{ComplexF64}:
 0.3180896176617806 + 3.7408349741629675e-16im
 0.6819103823382193 - 3.7408349741629675e-16im

"time = 11"

2-element Vector{Float64}:
 0.33898762151464157
 0.6610123784853584

2-element Vector{ComplexF64}:
 0.3395718896517468 + 1.4806984951853754e-16im
 0.6604281103482533 - 1.480698495185375e-16im

Indexed Edge 4 => 1 with index 10

"time = 1"

2-element Vector{Float64}:
 1.1891229846364981e-17
 1.0

2-element Vector{ComplexF64}:
 9.376674994732656e-33 - 1.974670425080817e-33im
    0.9999999999999999 + 1.8649090785144524e-33im

"time = 2"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 5.4210108624275214e-18im
 0.49999999999999994 + 5.421010862427523e-18im

"time = 3"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
 0.49999999999999994 - 6.248061245385559e-18im
 0.49999999999999994 + 6.2480612453855604e-18im

"time = 4"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 5.043409823081221e-18im
  0.4999999999999999 + 5.043409823081225e-18im

"time = 5"

2-element Vector{Float64}:
 0.5
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 1.521472020139819e-17im
 0.49999999999999994 + 1.521472020139819e-17im

"time = 6"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
  0.5000000000000001 - 4.126481632487422e-18im
 0.49999999999999983 + 4.126481632487422e-18im

"time = 7"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.5 + 4.2589219090820826e-18im
 0.5 - 4.2589219090820826e-18im

"time = 8"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.5000000000000001 + 2.6024556746999774e-18im
 0.49999999999999994 - 2.602455674699979e-18im

"time = 9"

2-element Vector{Float64}:
 0.49999999999999994
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 7.110318590382371e-18im
 0.49999999999999994 + 7.110318590382372e-18im

"time = 10"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
                 0.5 - 4.960192837372201e-18im
 0.49999999999999994 + 4.960192837372201e-18im

"time = 11"

2-element Vector{Float64}:
 0.5000000000000001
 0.5

2-element Vector{ComplexF64}:
 0.5000000000000001 + 4.1645958785256594e-18im
 0.4999999999999999 - 4.164595878525661e-18im

Indexed Edge 5 => 2 with index 11

"time = 1"

2-element Vector{Float64}:
 1.1891229846364981e-17
 1.0

2-element Vector{ComplexF64}:
 9.376674994732656e-33 - 1.974670425080817e-33im
    0.9999999999999999 + 1.8649090785144524e-33im

"time = 2"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 5.4210108624275214e-18im
 0.49999999999999994 + 5.421010862427523e-18im

"time = 3"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
 0.49999999999999994 - 6.248061245385559e-18im
 0.49999999999999994 + 6.2480612453855604e-18im

"time = 4"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 5.043409823081221e-18im
  0.4999999999999999 + 5.043409823081225e-18im

"time = 5"

2-element Vector{Float64}:
 0.5
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 1.521472020139819e-17im
 0.49999999999999994 + 1.521472020139819e-17im

"time = 6"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
  0.5000000000000001 - 4.126481632487422e-18im
 0.49999999999999983 + 4.126481632487422e-18im

"time = 7"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.5 + 4.2589219090820826e-18im
 0.5 - 4.2589219090820826e-18im

"time = 8"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.5000000000000001 + 2.6024556746999774e-18im
 0.49999999999999994 - 2.602455674699979e-18im

"time = 9"

2-element Vector{Float64}:
 0.49999999999999994
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 7.110318590382371e-18im
 0.49999999999999994 + 7.110318590382372e-18im

"time = 10"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
                 0.5 - 4.960192837372201e-18im
 0.49999999999999994 + 4.960192837372201e-18im

"time = 11"

2-element Vector{Float64}:
 0.5000000000000001
 0.5

2-element Vector{ComplexF64}:
 0.5000000000000001 + 4.1645958785256594e-18im
 0.4999999999999999 - 4.164595878525661e-18im

Indexed Edge 6 => 3 with index 12

"time = 1"

2-element Vector{Float64}:
 1.1891229846364981e-17
 1.0

2-element Vector{ComplexF64}:
 9.376674994732656e-33 - 1.974670425080817e-33im
    0.9999999999999999 + 1.8649090785144524e-33im

"time = 2"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 5.4210108624275214e-18im
 0.49999999999999994 + 5.421010862427523e-18im

"time = 3"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
 0.49999999999999994 - 6.248061245385559e-18im
 0.49999999999999994 + 6.2480612453855604e-18im

"time = 4"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 5.043409823081221e-18im
  0.4999999999999999 + 5.043409823081225e-18im

"time = 5"

2-element Vector{Float64}:
 0.5
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 1.521472020139819e-17im
 0.49999999999999994 + 1.521472020139819e-17im

"time = 6"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
  0.5000000000000001 - 4.126481632487422e-18im
 0.49999999999999983 + 4.126481632487422e-18im

"time = 7"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.5 + 4.2589219090820826e-18im
 0.5 - 4.2589219090820826e-18im

"time = 8"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.5000000000000001 + 2.6024556746999774e-18im
 0.49999999999999994 - 2.602455674699979e-18im

"time = 9"

2-element Vector{Float64}:
 0.49999999999999994
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 7.110318590382371e-18im
 0.49999999999999994 + 7.110318590382372e-18im

"time = 10"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
                 0.5 - 4.960192837372201e-18im
 0.49999999999999994 + 4.960192837372201e-18im

"time = 11"

2-element Vector{Float64}:
 0.5000000000000001
 0.5

2-element Vector{ComplexF64}:
 0.5000000000000001 + 4.1645958785256594e-18im
 0.4999999999999999 - 4.164595878525661e-18im

Indexed Edge 7 => 1 with index 13

"time = 1"

2-element Vector{Float64}:
 1.1891229846364981e-17
 1.0

2-element Vector{ComplexF64}:
 9.376674994732656e-33 - 1.974670425080817e-33im
    0.9999999999999999 + 1.8649090785144524e-33im

"time = 2"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 5.4210108624275214e-18im
 0.49999999999999994 + 5.421010862427523e-18im

"time = 3"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
 0.49999999999999994 - 6.248061245385559e-18im
 0.49999999999999994 + 6.2480612453855604e-18im

"time = 4"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 5.043409823081221e-18im
  0.4999999999999999 + 5.043409823081225e-18im

"time = 5"

2-element Vector{Float64}:
 0.5
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 1.521472020139819e-17im
 0.49999999999999994 + 1.521472020139819e-17im

"time = 6"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
  0.5000000000000001 - 4.126481632487422e-18im
 0.49999999999999983 + 4.126481632487422e-18im

"time = 7"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.5 + 4.2589219090820826e-18im
 0.5 - 4.2589219090820826e-18im

"time = 8"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.5000000000000001 + 2.6024556746999774e-18im
 0.49999999999999994 - 2.602455674699979e-18im

"time = 9"

2-element Vector{Float64}:
 0.49999999999999994
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 7.110318590382371e-18im
 0.49999999999999994 + 7.110318590382372e-18im

"time = 10"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
                 0.5 - 4.960192837372201e-18im
 0.49999999999999994 + 4.960192837372201e-18im

"time = 11"

2-element Vector{Float64}:
 0.5000000000000001
 0.5

2-element Vector{ComplexF64}:
 0.5000000000000001 + 4.1645958785256594e-18im
 0.4999999999999999 - 4.164595878525661e-18im

Indexed Edge 8 => 2 with index 14

"time = 1"

2-element Vector{Float64}:
 1.1891229846364981e-17
 1.0

2-element Vector{ComplexF64}:
 9.376674994732656e-33 - 1.974670425080817e-33im
    0.9999999999999999 + 1.8649090785144524e-33im

"time = 2"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 5.4210108624275214e-18im
 0.49999999999999994 + 5.421010862427523e-18im

"time = 3"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
 0.49999999999999994 - 6.248061245385559e-18im
 0.49999999999999994 + 6.2480612453855604e-18im

"time = 4"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 5.043409823081221e-18im
  0.4999999999999999 + 5.043409823081225e-18im

"time = 5"

2-element Vector{Float64}:
 0.5
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.4999999999999999 - 1.521472020139819e-17im
 0.49999999999999994 + 1.521472020139819e-17im

"time = 6"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
  0.5000000000000001 - 4.126481632487422e-18im
 0.49999999999999983 + 4.126481632487422e-18im

"time = 7"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.5 + 4.2589219090820826e-18im
 0.5 - 4.2589219090820826e-18im

"time = 8"

2-element Vector{Float64}:
 0.5000000000000001
 0.49999999999999994

2-element Vector{ComplexF64}:
  0.5000000000000001 + 2.6024556746999774e-18im
 0.49999999999999994 - 2.602455674699979e-18im

"time = 9"

2-element Vector{Float64}:
 0.49999999999999994
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 7.110318590382371e-18im
 0.49999999999999994 + 7.110318590382372e-18im

"time = 10"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
                 0.5 - 4.960192837372201e-18im
 0.49999999999999994 + 4.960192837372201e-18im

"time = 11"

2-element Vector{Float64}:
 0.5000000000000001
 0.5

2-element Vector{ComplexF64}:
 0.5000000000000001 + 4.1645958785256594e-18im
 0.4999999999999999 - 4.164595878525661e-18im