In [297]:
using Pkg
Pkg.activate(".")

  Activating project at `c:\Users\fefif\Desktop\PhD\Progetti\MatrixProductBP.jl`


In [298]:
using Revise
using MatrixProductBP, MatrixProductBP.Models
using Graphs, IndexedGraphs, Statistics, Random, LinearAlgebra, TensorTrains, SparseArrays
import ProgressMeter; ProgressMeter.ijulia_behavior(:clear)
using TensorTrains: summary_compact
using SparseArrays
using JLD2
include("bp_fourier.jl");

In [299]:
seed = 1
rng = MersenneTwister(seed)

T = 4
N = 4
A = [0 1 1 1;
     1 0 0 1;
     1 0 0 1;
     1 1 1 0]
# !!! Here the calculations are wrong for edge 1->2 !!!
# N = 5
# A = [0 1 1 1 1; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0]
# N = 6
# A = [0 1 1 1 0 0; 
#      1 0 0 0 1 0; 
#      1 0 0 0 0 1; 
#      1 0 0 0 0 0; 
#      0 1 0 0 0 0; 
#      0 0 1 0 0 0]
# N = 7
# A = [0 1 1 1 1 0 1;
#      1 0 0 0 1 0 0; 
#      1 0 0 0 0 1 0; 
#      1 0 0 0 0 0 0; 
#      1 1 0 0 0 0 0; 
#      0 0 1 0 0 0 0; 
#      1 0 0 0 0 0 0]

g = IndexedBiDiGraph(A)

# N = 10
# c = 3
# gg = erdos_renyi(N, c/N; seed)
# g = IndexedBiDiGraph(gg)
# A = zeros(Int,N,N)
# for i in CartesianIndices(A)
#      if !iszero(g.A[i])
#          A[i] = 1
#      end
# end
# rand!(rng, A.nzval, (-1,1))  # fill directed incidence matrix with rand(-1,1)
β = 1.0
J = 1
h = 0.0
m⁰ = 1.0
K = 50

svd_trunc=TruncBond(4)

A

4×4 Matrix{Int64}:
 0  1  1  1
 1  0  0  1
 1  0  0  1
 1  1  1  0

In [300]:
w = [fill(IntegerGlauberFactor([J*A[j,i] for j in inneighbors(g,i)], h, β), T+1) for i in vertices(g)]
ϕᵢ = [t == 0 ? [(1-m⁰)/2, (1+m⁰)/2] : ones(2) for t in 0:T]
bp = mpbp(g, w, fill(2,N), T; ϕ=fill(ϕᵢ,N))

for μ in bp.μ
    for a in μ
        a.=rand.(rng)
        # a.=1.0
    end
end
iterate!(bp, maxiter=1; svd_trunc)
# msg = deepcopy(bp.μ)
# jldsave("messages.jld2"; msg)

bp_fourier = deepcopy(bp)
;

In [301]:
iterate!(bp,maxiter=1; svd_trunc)

(1, CB_BP{ProgressMeter.ProgressUnknown, MatrixProductBP.var"#153#156"}(ProgressMeter.ProgressUnknown(false, false, 0, ProgressMeter.ProgressCore(:green, "Running MPBP: iter", 0.1, true, 0, VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}(IOContext(Base.PipeEndpoint(Base.Libc.WindowsRawSocket(0x0000000000000358) open, 0 bytes waiting)), VSCodeServer.io_send_callback), false, 1, 1, ReentrantLock(nothing, 0x00000000, 0x00, Base.GenericCondition{Base.Threads.SpinLock}(Base.IntrusiveLinkedList{Task}(nothing, nothing), Base.Threads.SpinLock(0)), (140706490380576, 140706490380576, 0)), 0, 1, false, false, 1.734623372474e9, 1.734623372474e9, 1.734623372474e9)), [[[2.0, 1.4680462684902087, 1.168288204202438, 1.7024637678660806, 1.6906831441177608], [2.0, 1.3592231440404587, 1.4742497286580778, 1.4184115749817208, 1.6625049857682797], [2.0, 1.2019356065262305, 1.7038975364675686, 1.4619563367976591, 1.367111099497259], [2.0, 1.9977805671926185, 1.975

In [302]:
iterate_fourier!(bp_fourier,K, maxiter=1, σ=1/50; svd_trunc)
;

In [303]:
import MatrixProductBP: marginalize
function marginalize(A::MPEM2{F}, var) where F
    if var==1
        return MPEM1{F}([@tullio b[m, n, xi] := a[m, n, xi, xj] for a in A]; z = A.z)
    elseif var==2
        return MPEM1{F}([@tullio b[m, n, xj] := a[m, n, xi, xj] for a in A]; z = A.z)
    end
end;

In [304]:
er = []
for e in edges(bp.g)
    for t in 1:T+1
        μ_marg = marginalize(bp.μ[idx(e)],1)
        marg = marginals(μ_marg)[t]
        μ_fourier_marg = marginalize(bp_fourier.μ[idx(e)],1)
        marg_fourier = marginals(μ_fourier_marg)[t]

        ind = argmax(abs.(marg))
        push!(er, abs(marg_fourier[ind]-marg[ind])/abs(marg[ind]))
    end
end

display(maximum(er))
display(argmax(er))

0.05527204066285778

12

In [305]:
node = 1
time = 5

ed = inedges(bp.g, node) |> first
@show ed
μ = bp.μ[idx(ed)]
μ_marg = marginalize(μ,1)
marg = marginals(μ_marg)[time]

ed_fourier = inedges(bp_fourier.g, node) |> first
@show ed_fourier
μ_fourier = bp_fourier.μ[idx(ed_fourier)]
μ_fourier_marg = marginalize(μ_fourier,1)
marg_fourier = marginals(μ_fourier_marg)[time]

display(marg)
display(marg_fourier);

2-element Vector{Float64}:
 0.3575044677500382
 0.6424955322499617

2-element Vector{Float64}:
 0.35760276347584247
 0.6423972365241575

ed = Indexed Edge 2 => 1 with index 4
ed_fourier = Indexed Edge 2 => 1 with index 4


In [306]:
for e in edges(bp.g)
    display(e)
end

Indexed Edge 1 => 2 with index 1

Indexed Edge 1 => 3 with index 2

Indexed Edge 1 => 4 with index 3

Indexed Edge 2 => 1 with index 4

Indexed Edge 2 => 4 with index 5

Indexed Edge 3 => 1 with index 6

Indexed Edge 3 => 4 with index 7

Indexed Edge 4 => 1 with index 8

Indexed Edge 4 => 2 with index 9

Indexed Edge 4 => 3 with index 10