In [151]:
using Pkg
Pkg.activate(".")

  Activating project at `~/Desktop/Continuous MPS/MatrixProductBP.jl`


In [152]:
using Revise
using MatrixProductBP, MatrixProductBP.Models
using Graphs, IndexedGraphs, Statistics, Random, LinearAlgebra, TensorTrains, SparseArrays
import ProgressMeter; ProgressMeter.ijulia_behavior(:clear)
using TensorTrains: summary_compact
using SparseArrays
using JLD2
include("bp_fourier.jl");

In [153]:
seed = 4
rng = MersenneTwister(seed)

T = 4
# N = 3
# A = [0 1 1; 
#      1 0 0;
#      1 0 0;]
# N = 4
# A = [0 1 0 0; 
#      1 0 1 0; 
#      0 1 0 1; 
#      0 0 1 0]
# N = 7
# A = [0 1 0 0 0 0 0; 
#      1 0 1 0 0 0 0; 
#      0 1 0 1 0 0 0;
#      0 0 1 0 1 0 0;
#      0 0 0 1 0 1 0;
#      0 0 0 0 1 0 1;
#      0 0 0 0 0 1 0]
# N = 4
# A = [0 1 1 1;
#      1 0 0 1;
#      1 0 0 1;
#      1 1 1 0]
# !!! Here the calculations are wrong for edge 1->2 !!!
# N = 5
# A = [0 1 1 1 1; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0; 
#      1 0 0 0 0]
# N = 6
# A = [0 1 1 1 0 0; 
#      1 0 0 0 1 0; 
#      1 0 0 0 0 1; 
#      1 0 0 0 0 0; 
#      0 1 0 0 0 0; 
#      0 0 1 0 0 0]
# N = 7
# A = [0 1 1 1 1 0 1;
#      1 0 0 0 1 0 0; 
#      1 0 0 0 0 1 0; 
#      1 0 0 0 0 0 0; 
#      1 1 0 0 0 0 0; 
#      0 0 1 0 0 0 0; 
#      1 0 0 0 0 0 0]
# N = 8
# A = [0 1 1 1 0 0 1 0;
#      1 0 0 0 1 0 0 1; 
#      1 0 0 0 0 1 0 0; 
#      1 0 0 0 0 0 0 0; 
#      0 1 0 0 0 0 0 0; 
#      0 0 1 0 0 0 0 0; 
#      1 0 0 0 0 0 0 0;
#      0 1 0 0 0 0 0 0]

# g = IndexedBiDiGraph(A)

N = 20
c = 3
gg = erdos_renyi(N, c/N; seed)
g = IndexedBiDiGraph(gg)
A = zeros(Int,N,N)
for i in CartesianIndices(A)
     if !iszero(g.A[i])
         A[i] = 1
     end
end

β = 1.0
J = 1
h = 0.0
m⁰ = 1.0
K = 100

svd_trunc=TruncBond(4)

A

20×20 Matrix{Int64}:
 0  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1
 1  0  0  0  0  1  0  0  1  0  0  0  0  1  0  1  0  0  0  0
 0  0  0  0  1  0  0  1  0  1  0  0  0  0  1  1  0  0  0  0
 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  0  0  0  0  0  1  1  0  1  0  0  1  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1
 0  0  0  1  0  0  0  0  1  0  0  0  0  0  0  1  0  0  0  0
 0  0  1  0  0  1  0  1  0  0  0  0  0  0  0  1  0  0  0  0
 0  0  0  1  0  1  0  0  0  0  1  1  0  0  0  0  0  0  0  1
 0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  1  0  0  1
 0  0  0  0  0  1  0  0  0  1  0  0  0  1  0  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
 0  0  1  0  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  1
 0  0  0  1  0  1  0  0  0  0  0  0  0  1  0  1  0  0  0  0
 0  0  1  1  0  0  0  1  1  0  0  1  1  0  1  0  0  1  0  0
 0  0  0  0  0  0  

In [154]:
w = [fill(IntegerGlauberFactor([J*A[j,i] for j in inneighbors(g,i)], h, β), T+1) for i in vertices(g)]
ϕᵢ = [t == 0 ? [(1-m⁰)/2, (1+m⁰)/2] : ones(2) for t in 0:T]
# ϕᵢ = [ones(2) for t in 0:T]
bp = mpbp(g, w, fill(2,N), T; ϕ=fill(ϕᵢ,N))

for μ in bp.μ
    for a in μ
        a.=rand.(rng)
        # a.=1.0
    end
end
# bp_fourier = deepcopy(bp)
iterate!(bp, maxiter=2; svd_trunc)

msg = deepcopy(bp.μ)
# jldsave("messages.jld2"; msg)

bp_fourier = convert_msg_beliefs(ComplexF64, bp)
# iterate_fourier!(bp_fourier,K, maxiter=1, σ=1/100; svd_trunc)
;

Running MPBP: iter 2    Time: 0:00:00

In [155]:
# for (k,ed) in enumerate(edges(bp.g))
#     display(ed)
#     display(bp.μ[idx(ed)][3])
# end

In [156]:
iterate!(bp,maxiter=1; svd_trunc)

(1, CB_BP{ProgressUnknown, MatrixProductBP.var"#162#165"}(ProgressUnknown(false, false, 0, ProgressMeter.ProgressCore(:green, "Running MPBP: iter", 0.1, true, 0, VSCodeServer.IJuliaCore.IJuliaStdio{Base.PipeEndpoint, typeof(VSCodeServer.io_send_callback)}(IOContext(Base.PipeEndpoint(RawFD(25) open, 0 bytes waiting)), VSCodeServer.io_send_callback), false, 1, 1, ReentrantLock(nothing, 0x00000000, 0x00, Base.GenericCondition{Base.Threads.SpinLock}(Base.IntrusiveLinkedList{Task}(nothing, nothing), Base.Threads.SpinLock(0)), (2, 2, 2)), 0, 1, false, false, 1.737714194167711e9, 1.737714194167711e9, 1.737714194167711e9)), [[[2.0, 1.9839772254535382, 1.632896927200663, 1.6098911496327768, 1.3055606050739306], [2.0, 1.9973336799498662, 1.9963704770571558, 1.976160040483573, 1.985694398766464], [2.0, 1.9999677253006862, 1.9941904380306, 1.9805439968405405, 1.9588280203330632], [2.0, 1.9998406056118185, 1.942559415653844, 1.8844139268551343, 1.8888182482943447], [2.0, 1.861257625807304, 1.863613

In [157]:
iterate_fourier!(bp_fourier,K, maxiter=1, σ=1/50; svd_trunc)
;

In [158]:
import MatrixProductBP: marginalize
function marginalize(A::MPEM2{F}, var) where F
    if var==1
        return MPEM1{F}([@tullio b[m, n, xi] := a[m, n, xi, xj] for a in A]; z = A.z)
    elseif var==2
        return MPEM1{F}([@tullio b[m, n, xj] := a[m, n, xi, xj] for a in A]; z = A.z)
    end
end;

In [159]:
er_b = []
ptr = []
for i in vertices(bp.g)
    margs = marginals(bp.b[i])
    margs_fourier = marginals(bp_fourier.b[i])
    for t in 1:T+1
        marg = margs[t]
        marg_fourier = margs_fourier[t]
        ind = argmax(abs.(marg))
        push!(er_b, abs(marg_fourier[ind]-marg[ind]))
        push!(ptr, (i, t))
    end
end

display(maximum(er_b))
display(ptr[argmax(er_b)])

0.08261184265503685

(16, 2)

In [160]:
er_μ = []
ptr = []
for e in edges(bp.g)
    μ_marg = marginalize(bp.μ[idx(e)],1)
    margs = marginals(μ_marg)
    μ_fourier_marg = marginalize(bp_fourier.μ[idx(e)],1)
    margs_fourier = marginals(μ_fourier_marg)
    for t in 1:T+1
        marg = margs[t]
        marg_fourier = margs_fourier[t]
        push!(er_μ, abs(marg_fourier[1]-marg[1]))
        push!(ptr, (e, t))
    end
end

display(maximum(er_μ))
display(ptr[argmax(er_μ)])

0.003257831768131547

(Indexed Edge 18 => 2 with index 65, 5)

In [161]:
er_μ = []
ptr = []
for e in edges(bp.g)
    μ = bp.μ[idx(e)]
    μ_fourier = bp_fourier.μ[idx(e)]
    push!(er_μ, norm2m(μ, μ_fourier)/(norm(μ)*norm(μ_fourier)))
    push!(ptr, (e))
end

display(maximum(abs, er_μ))
display(ptr[argmax(abs.(er_μ))])

0.00016915347785817568

Indexed Edge 18 => 7 with index 66

In [162]:
bp_fourier.μ[1][3]

4×4×2×2 Array{ComplexF64, 4}:
[:, :, 1, 1] =
  -0.00525906-0.0737442im    …     0.136038-0.207691im
   0.00893021+0.105618im          -0.191024+0.300184im
 -0.000370751+2.644e-5im          0.0106558+0.00697956im
 -0.000165035-0.000504468im     -0.00597651+0.0171732im

[:, :, 2, 1] =
  -0.0197438-0.276854im     …    -0.109634+0.167379im
 -0.00238243-0.0281771im          -0.01094+0.0171916im
 -0.00137796+9.82692e-5im      -0.00610062-0.00399591im
  4.45713e-5+0.000136242im      -0.0002486+0.000714341im

[:, :, 1, 2] =
  -0.00819235-0.114876im     …   -0.0873841+0.133411im
    0.0139111+0.164527im           0.122705-0.192824im
 -0.000108839+7.76185e-6im       0.00844524+0.00553164im
  -4.84488e-5-0.000148095im     -0.00473674+0.0136108im

[:, :, 2, 2] =
   -0.0307557-0.431266im    …     0.0704311-0.107528im
   -0.0037112-0.0438925im         0.0070281-0.0110443im
 -0.000405321+2.89054e-5im        -0.004464-0.00292392im
   1.31104e-5+4.0075e-5im      -0.000181902+0.000522686im

In [163]:
node = 2
time = 3

ed = inedges(bp.g, node) |> first
@show ed
μ = bp.μ[idx(ed)]
μ_marg = marginalize(μ,1)
marg = marginals(μ_marg)[time]

ed_fourier = inedges(bp_fourier.g, node) |> first
@show ed_fourier
μ_fourier = bp_fourier.μ[idx(ed_fourier)]
μ_fourier_marg = marginalize(μ_fourier,1)
marg_fourier = marginals(μ_fourier_marg)[time]

@show marg
@show marg_fourier;

ed = Indexed Edge 1 => 2 with index 1
ed_fourier = Indexed Edge 1 => 2 with index 1
marg = [0.266784653551786, 0.7332153464482141]
marg_fourier = ComplexF64[0.2669103108188348 + 8.115099437314236e-16im, 0.7330896891811652 - 8.115099437314236e-16im]


In [164]:
node = 1
time = 3

edd = outedges(bp.g, node)
for ed in edd
    display(ed)
    μ = bp.μ[idx(ed)]
    μ_marg = marginalize(μ,1)
    marg = marginals(μ_marg)[time]

    μ_fourier = bp_fourier.μ[idx(ed)]
    μ_fourier_marg = marginalize(μ_fourier,1)
    marg_fourier = marginals(μ_fourier_marg)[time]

    display(marg)
    display(marg_fourier)
end

Indexed Edge 1 => 2 with index 1

2-element Vector{Float64}:
 0.266784653551786
 0.7332153464482141

2-element Vector{ComplexF64}:
 0.2669103108188348 + 8.115099437314236e-16im
 0.7330896891811652 - 8.115099437314236e-16im

Indexed Edge 1 => 3 with index 2

2-element Vector{Float64}:
 0.26001636627695407
 0.7399836337230459

2-element Vector{ComplexF64}:
 0.26013913544220973 - 5.916666604347428e-17im
  0.7398608645577903 + 5.916666604347426e-17im

In [165]:
for ed in edges(bp.g)
    display(ed)

    μ = bp.μ[idx(ed)]
    μ_marg = marginalize(μ,1)
    μ_fourier = bp_fourier.μ[idx(ed)]
    μ_fourier_marg = marginalize(μ_fourier,1)

    for time in 1:T+1
        marg = marginals(μ_marg)[time]
        marg_fourier = marginals(μ_fourier_marg)[time]
        display("time = $time")
        display(marg)
        display(marg_fourier)
    end
end

Indexed Edge 1 => 2 with index 1

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.1311556129102756e-16 - 6.374926730794041e-17im
     0.9999999999999998 + 6.374926730794051e-17im

"time = 2"

2-element Vector{Float64}:
 0.256477230098429
 0.7435227699015711

2-element Vector{ComplexF64}:
 0.2565997427460958 + 3.954686974785061e-17im
 0.7434002572539041 - 3.9546869747850657e-17im

"time = 3"

2-element Vector{Float64}:
 0.266784653551786
 0.7332153464482141

2-element Vector{ComplexF64}:
 0.2669103108188348 + 8.115099437314236e-16im
 0.7330896891811652 - 8.115099437314236e-16im

"time = 4"

2-element Vector{Float64}:
 0.2674218242803597
 0.7325781757196402

2-element Vector{ComplexF64}:
 0.2675440267172879 + 8.319717547105033e-17im
  0.732455973282712 - 8.319717547105033e-17im

"time = 5"

2-element Vector{Float64}:
 0.26954960951084234
 0.7304503904891576

2-element Vector{ComplexF64}:
 0.26967144560580797 + 1.1526749117814183e-16im
   0.730328554394192 - 1.1526749117814183e-16im

Indexed Edge 1 => 3 with index 2

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 4.01096386935954e-17 - 7.96236359221994e-18im
   0.9999999999999999 + 7.962363592219935e-18im

"time = 2"

2-element Vector{Float64}:
 0.2560003872345749
 0.7439996127654251

2-element Vector{ComplexF64}:
 0.25612274759058684 - 2.6325205825736176e-17im
  0.7438772524094133 + 2.6325205825736188e-17im

"time = 3"

2-element Vector{Float64}:
 0.26001636627695407
 0.7399836337230459

2-element Vector{ComplexF64}:
 0.26013913544220973 - 5.916666604347428e-17im
  0.7398608645577903 + 5.916666604347426e-17im

"time = 4"

2-element Vector{Float64}:
 0.27317811938481135
 0.7268218806151886

2-element Vector{ComplexF64}:
 0.27330035810342845 + 6.239469138868624e-17im
  0.7266996418965715 - 6.239469138868624e-17im

"time = 5"

2-element Vector{Float64}:
 0.27700519250371425
 0.7229948074962858

2-element Vector{ComplexF64}:
 0.27712674499311885 + 1.9519550966772014e-16im
  0.7228732550068813 - 1.9519550966772012e-16im

Indexed Edge 2 => 1 with index 3

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.5886618067385894e-16 + 4.675642232253284e-19im
     0.9999999999999998 - 4.675642232253284e-19im

"time = 2"

2-element Vector{Float64}:
 0.06083760183607296
 0.9391623981639271

2-element Vector{ComplexF64}:
 0.0629343164831101 - 3.694705646968131e-17im
 0.9370656835168899 + 3.694705646968131e-17im

"time = 3"

2-element Vector{Float64}:
 0.06191276476837552
 0.9380872352316244

2-element Vector{ComplexF64}:
 0.06400435236176909 + 6.171192431491301e-17im
   0.935995647638231 - 6.1711924314913e-17im

"time = 4"

2-element Vector{Float64}:
 0.06627806679071378
 0.9337219332092862

2-element Vector{ComplexF64}:
 0.06846651056076128 - 1.953744753554403e-16im
  0.9315334894392387 + 1.9537447535544033e-16im

"time = 5"

2-element Vector{Float64}:
 0.06655329614055139
 0.9334467038594486

2-element Vector{ComplexF64}:
 0.06874030649486156 + 6.903389792563461e-17im
  0.9312596935051385 - 6.903389792563462e-17im

Indexed Edge 2 => 18 with index 4

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5631405043541622e-16 + 5.708980540998779e-17im
                     1.0 - 5.708980540998782e-17im

"time = 2"

2-element Vector{Float64}:
 0.061962542768388675
 0.9380374572316114

2-element Vector{ComplexF64}:
 0.06409477747145288 + 1.8481237101206753e-16im
   0.935905222528547 - 1.8481237101206735e-16im

"time = 3"

2-element Vector{Float64}:
 0.06863568626046206
 0.931364313739538

2-element Vector{ComplexF64}:
 0.07080159597145616 - 1.745792601202734e-17im
  0.9291984040285438 + 1.745792601202734e-17im

"time = 4"

2-element Vector{Float64}:
 0.08243341816090266
 0.9175665818390973

2-element Vector{ComplexF64}:
 0.0849898362998036 + 2.9971822737727877e-16im
 0.9150101637001965 - 2.9971822737727867e-16im

"time = 5"

2-element Vector{Float64}:
 0.08423711994990116
 0.9157628800500989

2-element Vector{ComplexF64}:
 0.08678138033331724 + 1.165449224679439e-16im
  0.9132186196666827 - 1.1654492246794372e-16im

Indexed Edge 2 => 20 with index 5

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.439202171999423e-16 + 4.520007290176724e-17im
     1.0000000000000002 - 4.5200072901767216e-17im

"time = 2"

2-element Vector{Float64}:
 0.06215239803871572
 0.9378476019612842

2-element Vector{ComplexF64}:
 0.0642891586223318 + 1.0945109827119488e-16im
 0.9357108413776681 - 1.0945109827119472e-16im

"time = 3"

2-element Vector{Float64}:
 0.06981252952796328
 0.9301874704720368

2-element Vector{ComplexF64}:
 0.07197438577616941 + 4.1226923153021836e-16im
  0.9280256142238307 - 4.1226923153021827e-16im

"time = 4"

2-element Vector{Float64}:
 0.08810484175393957
 0.9118951582460605

2-element Vector{ComplexF64}:
 0.09075624942781624 + 7.7156041020392e-17im
  0.9092437505721837 - 7.715604102039204e-17im

"time = 5"

2-element Vector{Float64}:
 0.09038331738833941
 0.9096166826116606

2-element Vector{ComplexF64}:
 0.09302360369431689 + 3.309612972855336e-16im
   0.906976396305683 - 3.309612972855337e-16im

Indexed Edge 3 => 1 with index 6

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.567463484741926e-16 + 2.083971007942586e-18im
    0.9999999999999999 - 2.0839710079426142e-18im

"time = 2"

2-element Vector{Float64}:
 0.0013126937754253006
 0.9986873062245747

2-element Vector{ComplexF64}:
 0.0016488307469384718 + 7.060234058722802e-16im
    0.9983511692530616 - 7.060234058722802e-16im

"time = 3"

2-element Vector{Float64}:
 0.0012251353741190001
 0.998774864625881

2-element Vector{ComplexF64}:
 0.0015344332625198717 - 4.2440523872831477e-17im
      0.99846556673748 + 4.2440523872831477e-17im

"time = 4"

2-element Vector{Float64}:
 0.0014794678908275607
 0.9985205321091725

2-element Vector{ComplexF64}:
 0.0018370487885595046 + 4.4413090654840785e-17im
    0.9981629512114404 - 4.44130906548408e-17im

"time = 5"

2-element Vector{Float64}:
 0.0032157908055373058
 0.9967842091944628

2-element Vector{ComplexF64}:
 0.003826451882285098 + 4.583065663530765e-17im
   0.9961735481177149 - 4.5830656635307655e-17im

Indexed Edge 3 => 6 with index 7

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -6.860902859526e-17 - 1.4603020649445704e-16im
                 1.0 + 1.4603020649445729e-16im

"time = 2"

2-element Vector{Float64}:
 0.0012947652626209326
 0.998705234737379

2-element Vector{ComplexF64}:
 0.0016263190603324083 + 2.491421671512017e-16im
    0.9983736809396675 - 2.4914216715120155e-16im

"time = 3"

2-element Vector{Float64}:
 0.002351635879865399
 0.9976483641201347

2-element Vector{ComplexF64}:
 0.0028515610501994968 - 1.3900675176576945e-16im
    0.9971484389498004 + 1.390067517657695e-16im

"time = 4"

2-element Vector{Float64}:
 0.0025998888355014582
 0.9974001111644986

2-element Vector{ComplexF64}:
 0.003149186610117076 + 1.3489623625187756e-16im
   0.9968508133898829 - 1.3489623625187746e-16im

"time = 5"

2-element Vector{Float64}:
 0.002412664356261123
 0.9975873356437389

2-element Vector{ComplexF64}:
 0.0030103218316594217 - 1.4003774275955642e-17im
    0.9969896781683406 + 1.4003774275955587e-17im

Indexed Edge 3 => 9 with index 8

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 4.0207954724993686e-17 + 1.5144256176159516e-16im
                    1.0 - 1.514425617615951e-16im

"time = 2"

2-element Vector{Float64}:
 0.0013085096297435616
 0.9986914903702565

2-element Vector{ComplexF64}:
 0.0016435765269826761 + 3.507804688984867e-16im
    0.9983564234730173 - 3.507804688984868e-16im

"time = 3"

2-element Vector{Float64}:
 0.0022022572235274786
 0.9977977427764725

2-element Vector{ComplexF64}:
 0.0026722780090841875 - 9.87502744288632e-17im
    0.9973277219909159 + 9.875027442886325e-17im

"time = 4"

2-element Vector{Float64}:
 0.0026641703767563258
 0.9973358296232437

2-element Vector{ComplexF64}:
 0.003222256483779054 - 5.706679879872699e-16im
   0.9967777435162211 + 5.706679879872698e-16im

"time = 5"

2-element Vector{Float64}:
 0.0039435964562385285
 0.9960564035437615

2-element Vector{ComplexF64}:
 0.004787375496011504 + 2.438188058397476e-16im
   0.9952126245039886 - 2.438188058397476e-16im

Indexed Edge 3 => 14 with index 9

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 8.44370300764725e-17 + 1.3946390389905772e-16im
   0.9999999999999998 - 1.3946390389905812e-16im

"time = 2"

2-element Vector{Float64}:
 0.001278430169514469
 0.9987215698304855

2-element Vector{ComplexF64}:
 0.0016058067227356664 + 4.935806735732573e-16im
    0.9983941932772643 - 4.935806735732572e-16im

"time = 3"

2-element Vector{Float64}:
 0.002206873329648859
 0.9977931266703511

2-element Vector{ComplexF64}:
 0.0026779597133144936 + 1.8127760121556338e-16im
    0.9973220402866854 - 1.812776012155634e-16im

"time = 4"

2-element Vector{Float64}:
 0.0025639820096092594
 0.9974360179903907

2-element Vector{ComplexF64}:
 0.0031073559521940064 - 6.698675819905184e-17im
    0.9968926440478059 + 6.698675819905178e-17im

"time = 5"

2-element Vector{Float64}:
 0.003974537161980429
 0.9960254628380196

2-element Vector{ComplexF64}:
 0.0047799743154922 + 8.763383432403101e-17im
 0.9952200256845077 - 8.763383432403116e-17im

Indexed Edge 3 => 16 with index 10

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 5.646559671418471e-17 + 1.4695420516842097e-16im
    0.9999999999999999 - 1.4695420516842105e-16im

"time = 2"

2-element Vector{Float64}:
 0.0013118872264929662
 0.9986881127735071

2-element Vector{ComplexF64}:
 0.0016478174328131284 + 5.177497177089117e-16im
    0.9983521825671868 - 5.177497177089117e-16im

"time = 3"

2-element Vector{Float64}:
 0.002222026953997378
 0.9977779730460026

2-element Vector{ComplexF64}:
 0.002694492596892441 + 6.917937612908275e-16im
   0.9973055074031075 - 6.917937612908274e-16im

"time = 4"

2-element Vector{Float64}:
 0.0027019699700389223
 0.9972980300299611

2-element Vector{ComplexF64}:
 0.003265808744404569 - 1.882886814973868e-16im
   0.9967341912555954 + 1.882886814973868e-16im

"time = 5"

2-element Vector{Float64}:
 0.0039055722913077604
 0.9960944277086923

2-element Vector{ComplexF64}:
 0.00475723183856726 + 1.1362650519900207e-16im
  0.9952427681614326 - 1.1362650519900204e-16im

Indexed Edge 4 => 5 with index 11

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5499168226314165e-16 + 3.037968325248908e-17im
      1.0000000000000002 - 3.037968325248908e-17im

"time = 2"

2-element Vector{Float64}:
 0.0012892765700732159
 0.9987107234299267

2-element Vector{ComplexF64}:
 0.0016194361333279604 + 3.725001947991619e-16im
     0.998380563866672 - 3.72500194799162e-16im

"time = 3"

2-element Vector{Float64}:
 0.0014319171458952173
 0.9985680828541048

2-element Vector{ComplexF64}:
 0.001777234178280363 + 1.92720173245604e-16im
   0.9982227658217196 - 1.92720173245604e-16im

"time = 4"

2-element Vector{Float64}:
 0.0016434991864662126
 0.9983565008135338

2-element Vector{ComplexF64}:
 0.0020278330446325335 - 1.000672949317025e-16im
    0.9979721669553675 + 1.0006729493170254e-16im

"time = 5"

2-element Vector{Float64}:
 0.0037342518307724084
 0.9962657481692276

2-element Vector{ComplexF64}:
 0.0044379326488914244 + 1.6243267617716545e-16im
    0.9955620673511086 - 1.6243267617716548e-16im

Indexed Edge 4 => 8 with index 12

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5819139959330563e-16 - 7.562954472481447e-18im
                     1.0 + 7.562954472481466e-18im

"time = 2"

2-element Vector{Float64}:
 0.0012537881484467456
 0.9987462118515533

2-element Vector{ComplexF64}:
 0.0015748613460836046 + 3.43933712983253e-16im
    0.9984251386539164 - 3.4393371298325296e-16im

"time = 3"

2-element Vector{Float64}:
 0.008188029072310053
 0.9918119709276899

2-element Vector{ComplexF64}:
 0.009533353665790827 + 3.175537473583508e-16im
   0.9904666463342092 - 3.1755374735835077e-16im

"time = 4"

2-element Vector{Float64}:
 0.008730016611399213
 0.9912699833886007

2-element Vector{ComplexF64}:
 0.010159965464911156 - 1.2344923863223978e-16im
   0.9898400345350888 + 1.2344923863223976e-16im

"time = 5"

2-element Vector{Float64}:
 0.012576705758720615
 0.9874232942412794

2-element Vector{ComplexF64}:
 0.014393743607955872 + 3.465639620791754e-16im
   0.9856062563920441 - 3.465639620791754e-16im

Indexed Edge 4 => 10 with index 13

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5693694505416657e-16 - 4.0945941788039604e-18im
                     1.0 + 4.094594178803994e-18im

"time = 2"

2-element Vector{Float64}:
 0.0013039316921188869
 0.9986960683078812

2-element Vector{ComplexF64}:
 0.0016378116392992631 + 3.5510199418789435e-16im
    0.9983621883607008 - 3.551019941878944e-16im

"time = 3"

2-element Vector{Float64}:
 0.00877393192438669
 0.9912260680756133

2-element Vector{ComplexF64}:
 0.01018231543714305 + 3.6787216886981445e-17im
   0.989817684562857 - 3.678721688698147e-17im

"time = 4"

2-element Vector{Float64}:
 0.00892059576592977
 0.9910794042340701

2-element Vector{ComplexF64}:
 0.010370886112583098 + 1.2051832111556732e-16im
   0.9896291138874169 - 1.205183211155673e-16im

"time = 5"

2-element Vector{Float64}:
 0.010806054633949314
 0.9891939453660507

2-element Vector{ComplexF64}:
 0.012500575616979646 + 1.893179607258388e-16im
   0.9874994243830204 - 1.8931796072583874e-16im

Indexed Edge 4 => 15 with index 14

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.5662747851848353e-16 + 2.796824986779353e-18im
     0.9999999999999999 - 2.796824986779376e-18im

"time = 2"

2-element Vector{Float64}:
 0.0012921195665815922
 0.9987078804334184

2-element Vector{ComplexF64}:
 0.0016229744632092875 + 4.683355971245851e-16im
    0.9983770255367908 - 4.683355971245851e-16im

"time = 3"

2-element Vector{Float64}:
 0.008531070904693055
 0.9914689290953069

2-element Vector{ComplexF64}:
 0.00990370334922967 + 1.3362177621748492e-16im
  0.9900962966507704 - 1.336217762174848e-16im

"time = 4"

2-element Vector{Float64}:
 0.009134363165757164
 0.9908656368342429

2-element Vector{ComplexF64}:
 0.010601820891619299 + 2.2914941503441597e-16im
   0.9893981791083807 - 2.29149415034416e-16im

"time = 5"

2-element Vector{Float64}:
 0.01453315001877138
 0.9854668499812287

2-element Vector{ComplexF64}:
 0.016507644815630235 + 2.229258864059467e-16im
   0.9834923551843698 - 2.2292588640594676e-16im

Indexed Edge 4 => 16 with index 15

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.566785150068562e-16 + 5.865340641421748e-18im
     1.0000000000000002 - 5.865340641421746e-18im

"time = 2"

2-element Vector{Float64}:
 0.0012962891160254854
 0.9987037108839746

2-element Vector{ComplexF64}:
 0.0016282080274847165 + 5.495036168045592e-16im
    0.9983717919725154 - 5.495036168045592e-16im

"time = 3"

2-element Vector{Float64}:
 0.008561534576326434
 0.9914384654236736

2-element Vector{ComplexF64}:
 0.009935547104501032 - 9.925469756612531e-17im
    0.990064452895499 + 9.925469756612531e-17im

"time = 4"

2-element Vector{Float64}:
 0.009188972289612058
 0.9908110277103879

2-element Vector{ComplexF64}:
 0.010661810290646865 + 2.4058486062363775e-16im
   0.9893381897093532 - 2.4058486062363775e-16im

"time = 5"

2-element Vector{Float64}:
 0.014652786638039142
 0.9853472133619608

2-element Vector{ComplexF64}:
 0.016639552984135633 + 5.0251514116812044e-18im
   0.9833604470158643 - 5.025151411681205e-18im

Indexed Edge 5 => 4 with index 16

"time = 1"

2-element Vector{Float64}:
 1.1891229846364983e-17
 1.0

2-element Vector{ComplexF64}:
 1.279531428878262e-32 - 1.5910738166749782e-33im
                   1.0 + 2.0358686031456502e-33im

"time = 2"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
  0.5000000000000001 - 5.421010862427533e-18im
 0.49999999999999994 + 5.421010862427533e-18im

"time = 3"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 5.8966280726613325e-18im
 0.49999999999999994 + 5.8966280726613325e-18im

"time = 4"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
                0.5 - 5.952512907192562e-18im
 0.4999999999999999 + 5.952512907192562e-18im

"time = 5"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
 0.5000000000000001 - 1.1651910620020017e-17im
 0.4999999999999999 + 1.1651910620020017e-17im

Indexed Edge 6 => 3 with index 17

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5692758032658357e-16 - 3.9336421668825863e-19im
      1.0000000000000002 + 3.933642166882139e-19im

"time = 2"

2-element Vector{Float64}:
 0.00017358591383894486
 0.999826414086161

2-element Vector{ComplexF64}:
 0.0002598874656895805 - 4.591176509224966e-17im
    0.9997401125343104 + 4.5911765092249683e-17im

"time = 3"

2-element Vector{Float64}:
 0.00017601509308413894
 0.9998239849069158

2-element Vector{ComplexF64}:
 0.00026280601153611704 - 1.777707275527432e-16im
     0.9997371939884638 + 1.7777072755274319e-16im

"time = 4"

2-element Vector{Float64}:
 0.00021038750737088164
 0.9997896124926292

2-element Vector{ComplexF64}:
 0.0003118584631092612 - 2.1016952292929764e-16im
    0.9996881415368908 + 2.101695229292977e-16im

"time = 5"

2-element Vector{Float64}:
 0.00047838231906618056
 0.9995216176809338

2-element Vector{ComplexF64}:
 0.0006908842221929866 - 2.404349684296783e-16im
     0.999309115777807 + 2.404349684296783e-16im

Indexed Edge 6 => 9 with index 18

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -7.711397290806702e-17 - 1.4393812404606568e-16im
     1.0000000000000002 + 1.439381240460657e-16im

"time = 2"

2-element Vector{Float64}:
 0.00017264429834516347
 0.9998273557016548

2-element Vector{ComplexF64}:
 0.0002584750563228162 - 6.169082003161107e-17im
    0.9997415249436773 + 6.169082003161102e-17im

"time = 3"

2-element Vector{Float64}:
 0.00017359168349371568
 0.9998264083165063

2-element Vector{ComplexF64}:
 0.00025952853381389996 - 2.232445215026048e-16im
     0.9997404714661862 + 2.2324452150260483e-16im

"time = 4"

2-element Vector{Float64}:
 0.00020624976039730256
 0.9997937502396027

2-element Vector{ComplexF64}:
 0.00030642084438260904 - 3.5410911691578895e-16im
     0.9996935791556174 + 3.54109116915789e-16im

"time = 5"

2-element Vector{Float64}:
 0.00047213316457494396
 0.999527866835425

2-element Vector{ComplexF64}:
 0.0006832387703113647 + 9.620409671473743e-17im
    0.9993167612296885 - 9.620409671473782e-17im

Indexed Edge 6 => 10 with index 19

"time = 1"

2-element Vector{Float64}:
 -5.8802369410838836e-21
  1.0

2-element Vector{ComplexF64}:
 -6.4462251589825e-17 + 1.4224871665094104e-17im
                  1.0 - 1.4224871665094104e-17im

"time = 2"

2-element Vector{Float64}:
 0.0001726376926053229
 0.9998273623073947

2-element Vector{ComplexF64}:
 0.00025846555044693314 + 8.621174799352389e-18im
      0.999741534449553 - 8.621174799352394e-18im

"time = 3"

2-element Vector{Float64}:
 0.00018078483289870004
 0.9998192151671013

2-element Vector{ComplexF64}:
 0.0002700739464525078 + 3.3862694349468805e-17im
    0.9997299260535476 - 3.38626943494688e-17im

"time = 4"

2-element Vector{Float64}:
 0.00018664405434440742
 0.9998133559456556

2-element Vector{ComplexF64}:
 0.0002786264019908309 - 1.2807209284545306e-16im
    0.9997213735980092 + 1.2807209284545306e-16im

"time = 5"

2-element Vector{Float64}:
 0.00019033630305704334
 0.999809663696943

2-element Vector{ComplexF64}:
 0.0002853117705540354 - 1.8840764418874392e-16im
     0.999714688229446 + 1.8840764418874392e-16im

Indexed Edge 6 => 12 with index 20

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 7.65621911649648e-17 + 1.443625017535008e-16im
   0.9999999999999998 - 1.443625017535007e-16im

"time = 2"

2-element Vector{Float64}:
 0.00017368189802445367
 0.9998263181019755

2-element Vector{ComplexF64}:
 0.0002600289823340502 - 8.491376013044114e-17im
     0.999739971017666 + 8.491376013044109e-17im

"time = 3"

2-element Vector{Float64}:
 0.0001759648108904245
 0.9998240351891097

2-element Vector{ComplexF64}:
 0.000262852360947709 - 8.254126854555575e-17im
   0.9997371476390522 + 8.254126854555594e-17im

"time = 4"

2-element Vector{Float64}:
 0.000211130516351041
 0.999788869483649

2-element Vector{ComplexF64}:
 0.00031323695731830904 - 3.836354131023285e-16im
     0.9996867630426817 + 3.8363541310232863e-16im

"time = 5"

2-element Vector{Float64}:
 0.000477566432318587
 0.9995224335676814

2-element Vector{ComplexF64}:
 0.0006902553135017283 - 5.905905634911293e-16im
    0.9993097446864982 + 5.905905634911288e-16im

Indexed Edge 6 => 15 with index 21

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -5.547839435739003e-18 + 1.2222394596676569e-18im
                    1.0 - 1.2222394596676426e-18im

"time = 2"

2-element Vector{Float64}:
 0.0001722445734935649
 0.9998277554265065

2-element Vector{ComplexF64}:
 0.00025787691148809126 - 8.172371923610704e-17im
      0.999742123088512 + 8.172371923610694e-17im

"time = 3"

2-element Vector{Float64}:
 0.0001733581811277477
 0.9998266418188723

2-element Vector{ComplexF64}:
 0.0002592023293686127 - 2.4192423054843087e-17im
    0.9997407976706313 + 2.4192423054843342e-17im

"time = 4"

2-element Vector{Float64}:
 0.00020628776608464801
 0.9997937122339153

2-element Vector{ComplexF64}:
 0.00030647073093577234 - 5.229651687961712e-16im
     0.9996935292690643 + 5.229651687961712e-16im

"time = 5"

2-element Vector{Float64}:
 0.00046777100043802187
 0.999532228999562

2-element Vector{ComplexF64}:
 0.0006772935002608306 - 7.524404050134636e-16im
    0.9993227064997391 + 7.524404050134635e-16im

Indexed Edge 6 => 19 with index 22

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -2.4725270243468222e-17 + 1.656594941123015e-16im
                     1.0 - 1.656594941123017e-16im

"time = 2"

2-element Vector{Float64}:
 0.00017388952941232324
 0.9998261104705877

2-element Vector{ComplexF64}:
 0.0002603394948829004 + 2.362987945984998e-16im
    0.9997396605051171 - 2.362987945984995e-16im

"time = 3"

2-element Vector{Float64}:
 0.00017359769442068027
 0.9998264023055793

2-element Vector{ComplexF64}:
 0.0002595263165697888 - 2.0774314732426454e-17im
    0.9997404736834301 + 2.0774314732426297e-17im

"time = 4"

2-element Vector{Float64}:
 0.00020516882512645995
 0.9997948311748736

2-element Vector{ComplexF64}:
 0.0003049161690553771 - 6.518959596895877e-16im
    0.9996950838309447 + 6.518959596895877e-16im

"time = 5"

2-element Vector{Float64}:
 0.00047368942296345344
 0.9995263105770366

2-element Vector{ComplexF64}:
 0.0006843350385310293 - 7.342361440846246e-16im
    0.9993156649614691 + 7.342361440846245e-16im

Indexed Edge 7 => 18 with index 23

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.455045231924073e-16 - 7.907171717674737e-18im
     1.0000000000000002 + 7.907171717674995e-18im

"time = 2"

2-element Vector{Float64}:
 0.25899284540324863
 0.7410071545967515

2-element Vector{ComplexF64}:
 0.2591161379409665 + 1.6019713091214063e-16im
 0.7408838620590336 - 1.6019713091214063e-16im

"time = 3"

2-element Vector{Float64}:
 0.2589935466927035
 0.7410064533072964

2-element Vector{ComplexF64}:
 0.2591168390847458 + 1.2564041403258746e-16im
 0.7408831609152543 - 1.256404140325875e-16im

"time = 4"

2-element Vector{Float64}:
 0.2590008345746751
 0.7409991654253248

2-element Vector{ComplexF64}:
 0.2591241266684097 - 2.262136963116243e-16im
 0.7408758733315902 + 2.2621369631162434e-16im

"time = 5"

2-element Vector{Float64}:
 0.25903075512572726
 0.7409692448742726

2-element Vector{ComplexF64}:
 0.2591540451227534 + 2.266603501497019e-16im
 0.7408459548772466 - 2.26660350149702e-16im

Indexed Edge 7 => 20 with index 24

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.4576116164568867e-16 - 1.4816268917777784e-17im
     0.9999999999999998 + 1.481626891777783e-17im

"time = 2"

2-element Vector{Float64}:
 0.2589931064913563
 0.7410068935086437

2-element Vector{ComplexF64}:
 0.2591163991098997 + 1.2913431012261803e-16im
 0.7408836008901003 - 1.2913431012261805e-16im

"time = 3"

2-element Vector{Float64}:
 0.2601859692765007
 0.7398140307234995

2-element Vector{ComplexF64}:
 0.260308651657476 - 3.5962023487694365e-17im
 0.739691348342524 + 3.596202348769435e-17im

"time = 4"

2-element Vector{Float64}:
 0.27517684731618386
 0.724823152683816

2-element Vector{ComplexF64}:
 0.2752989118404542 + 3.8490771856029985e-16im
 0.7247010881595458 - 3.849077185602998e-16im

"time = 5"

2-element Vector{Float64}:
 0.27540541137779667
 0.7245945886222034

2-element Vector{ComplexF64}:
 0.27552733254272854 - 4.6248089996610503e-17im
  0.7244726674572713 + 4.624808999661052e-17im

Indexed Edge 8 => 4 with index 25

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.59239496718424e-16 - 3.5389479159585224e-17im
   0.9999999999999998 + 3.538947915958521e-17im

"time = 2"

2-element Vector{Float64}:
 0.061070313145732746
 0.9389296868542673

2-element Vector{ComplexF64}:
 0.0631745084969288 + 2.6386657266072022e-17im
  0.936825491503071 - 2.6386657266072028e-17im

"time = 3"

2-element Vector{Float64}:
 0.06094238929327665
 0.9390576107067233

2-element Vector{ComplexF64}:
 0.06303689376773908 - 4.9482752214102034e-18im
  0.9369631062322611 + 4.9482752214102096e-18im

"time = 4"

2-element Vector{Float64}:
 0.06160246470053294
 0.9383975352994671

2-element Vector{ComplexF64}:
 0.06371550880149861 + 4.2149067687391763e-17im
  0.9362844911985014 - 4.2149067687391775e-17im

"time = 5"

2-element Vector{Float64}:
 0.0616848310584154
 0.9383151689415845

2-element Vector{ComplexF64}:
 0.06379815584899258 - 7.547276480521448e-17im
  0.9362018441510074 + 7.547276480521442e-17im

Indexed Edge 8 => 9 with index 26

"time = 1"

2-element Vector{Float64}:
 -6.71405650953219e-19
  1.0

2-element Vector{ComplexF64}:
 1.4123858655780308e-16 - 4.055284092631567e-17im
     0.9999999999999998 + 4.0552840926315623e-17im

"time = 2"

2-element Vector{Float64}:
 0.06081558835442723
 0.9391844116455728

2-element Vector{ComplexF64}:
 0.06290767653218678 + 2.28046189917511e-16im
  0.9370923234678131 - 2.28046189917511e-16im

"time = 3"

2-element Vector{Float64}:
 0.06085768514844206
 0.939142314851558

2-element Vector{ComplexF64}:
 0.06295942974980616 + 2.348775758711765e-16im
  0.9370405702501939 - 2.348775758711765e-16im

"time = 4"

2-element Vector{Float64}:
 0.06140678927223698
 0.938593210727763

2-element Vector{ComplexF64}:
 0.0636215832904943 + 1.7356985279809499e-16im
 0.9363784167095057 - 1.7356985279809499e-16im

"time = 5"

2-element Vector{Float64}:
 0.06145911035388953
 0.9385408896461105

2-element Vector{ComplexF64}:
 0.06368098247214614 - 1.3189766442127057e-16im
   0.936319017527854 + 1.3189766442127057e-16im

Indexed Edge 8 => 16 with index 27

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.4006898947236214e-16 + 8.656040000783824e-18im
                     1.0 - 8.65604000078383e-18im

"time = 2"

2-element Vector{Float64}:
 0.061044119597156415
 0.9389558804028435

2-element Vector{ComplexF64}:
 0.06314341571372656 - 2.217405595841006e-17im
  0.9368565842862735 + 2.2174055958410048e-17im

"time = 3"

2-element Vector{Float64}:
 0.060962093399663325
 0.9390379066003367

2-element Vector{ComplexF64}:
 0.06306160150337879 + 2.837631528922327e-16im
  0.9369383984966212 - 2.837631528922327e-16im

"time = 4"

2-element Vector{Float64}:
 0.06216550355660083
 0.9378344964433992

2-element Vector{ComplexF64}:
 0.06439662720669832 + 1.0980609443225179e-16im
  0.9356033727933016 - 1.0980609443225178e-16im

"time = 5"

2-element Vector{Float64}:
 0.062279799063593294
 0.9377202009364067

2-element Vector{ComplexF64}:
 0.06451780505197939 + 7.697751748034754e-17im
  0.9354821949480207 - 7.697751748034758e-17im

Indexed Edge 9 => 3 with index 28

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5092916007145867e-16 + 4.223837255557306e-17im
                     1.0 - 4.2238372555573026e-17im

"time = 2"

2-element Vector{Float64}:
 0.009160997964633183
 0.9908390020353668

2-element Vector{ComplexF64}:
 0.010252253648036893 - 3.1194438314210954e-17im
    0.989747746351963 + 3.119443831421098e-17im

"time = 3"

2-element Vector{Float64}:
 0.009779869640316297
 0.9902201303596837

2-element Vector{ComplexF64}:
 0.010904756372685414 + 3.7148625150397484e-16im
   0.9890952436273146 - 3.714862515039749e-16im

"time = 4"

2-element Vector{Float64}:
 0.010050303198170402
 0.9899496968018295

2-element Vector{ComplexF64}:
 0.011218120920275361 - 3.6772712013276725e-17im
   0.9887818790797247 + 3.6772712013276663e-17im

"time = 5"

2-element Vector{Float64}:
 0.010083239798994054
 0.9899167602010059

2-element Vector{ComplexF64}:
 0.01125633941513853 + 2.2870019660611963e-16im
  0.9887436605848616 - 2.287001966061196e-16im

Indexed Edge 9 => 6 with index 29

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.0559617530267348e-17 - 2.5692091965511084e-17im
                     1.0 + 2.56920919655111e-17im

"time = 2"

2-element Vector{Float64}:
 0.009158455523849012
 0.990841544476151

2-element Vector{ComplexF64}:
 0.010248845565883452 + 3.875344163585312e-16im
   0.9897511544341167 - 3.875344163585312e-16im

"time = 3"

2-element Vector{Float64}:
 0.00979001601781306
 0.990209983982187

2-element Vector{ComplexF64}:
 0.01091638373188995 + 5.251419567313934e-16im
    0.98908361626811 - 5.251419567313934e-16im

"time = 4"

2-element Vector{Float64}:
 0.010079802891682038
 0.9899201971083179

2-element Vector{ComplexF64}:
 0.011254993761461066 + 2.5936909249141357e-16im
   0.9887450062385389 - 2.5936909249141347e-16im

"time = 5"

2-element Vector{Float64}:
 0.010120774476477804
 0.9898792255235221

2-element Vector{ComplexF64}:
 0.011303092261146588 + 3.481628340344616e-16im
   0.9886969077388535 - 3.481628340344615e-16im

Indexed Edge 9 => 8 with index 30

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 2.7522424797440755e-17 - 1.1570757629304636e-17im
                    1.0 + 1.157075762930477e-17im

"time = 2"

2-element Vector{Float64}:
 0.009158396282884894
 0.9908416037171152

2-element Vector{ComplexF64}:
 0.010248745782122691 + 2.4914666031418193e-16im
   0.9897512542178774 - 2.4914666031418193e-16im

"time = 3"

2-element Vector{Float64}:
 0.009174153283644406
 0.9908258467163557

2-element Vector{ComplexF64}:
 0.010270014959351516 + 3.946636762987451e-16im
   0.9897299850406485 - 3.946636762987451e-16im

"time = 4"

2-element Vector{Float64}:
 0.00919477464077591
 0.9908052253592241

2-element Vector{ComplexF64}:
 0.010297150667967554 + 6.452079224390781e-16im
   0.9897028493320325 - 6.452079224390779e-16im

"time = 5"

2-element Vector{Float64}:
 0.00920510489543276
 0.9907948951045672

2-element Vector{ComplexF64}:
 0.010309665398336328 + 6.274805967616864e-17im
   0.9896903346016637 - 6.274805967616847e-17im

Indexed Edge 9 => 16 with index 31

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.0565973900981224e-16 + 1.1648990089605546e-16im
                     1.0 - 1.1648990089605546e-16im

"time = 2"

2-element Vector{Float64}:
 0.009158072712670016
 0.9908419272873299

2-element Vector{ComplexF64}:
 0.010248374387448717 + 2.5205240827509773e-16im
   0.9897516256125514 - 2.5205240827509763e-16im

"time = 3"

2-element Vector{Float64}:
 0.009791538366937972
 0.9902084616330621

2-element Vector{ComplexF64}:
 0.010919444183620354 + 4.035432902371692e-17im
   0.9890805558163795 - 4.0354329023717153e-17im

"time = 4"

2-element Vector{Float64}:
 0.010081397285813467
 0.9899186027141865

2-element Vector{ComplexF64}:
 0.011258630232626144 - 2.406204986529712e-18im
   0.9887413697673738 + 2.4062049865297646e-18im

"time = 5"

2-element Vector{Float64}:
 0.010120242250693107
 0.9898797577493069

2-element Vector{ComplexF64}:
 0.011304863924739256 - 1.9979525181082764e-17im
   0.9886951360752608 + 1.997952518108267e-17im

Indexed Edge 10 => 4 with index 32

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 9.394258102292951e-17 - 1.9978059100281622e-17im
    0.9999999999999998 + 1.997805910028167e-17im

"time = 2"

2-element Vector{Float64}:
 0.0013500493106016838
 0.9986499506893983

2-element Vector{ComplexF64}:
 0.0016957347712856317 + 2.9443289596217336e-16im
    0.9983042652287143 - 2.944328959621733e-16im

"time = 3"

2-element Vector{Float64}:
 0.0014237783048886145
 0.9985762216951114

2-element Vector{ComplexF64}:
 0.0017751198547472104 + 2.539628899460449e-16im
    0.9982248801452528 - 2.5396288994604483e-16im

"time = 4"

2-element Vector{Float64}:
 0.005018789538661194
 0.9949812104613388

2-element Vector{ComplexF64}:
 0.005910467028055461 + 1.7484267081551201e-16im
   0.9940895329719445 - 1.7484267081551194e-16im

"time = 5"

2-element Vector{Float64}:
 0.002917474503116148
 0.9970825254968838

2-element Vector{ComplexF64}:
 0.003493226366807983 + 5.656359871913996e-17im
    0.996506773633192 - 5.656359871913996e-17im

Indexed Edge 10 => 6 with index 33

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.5703317176505106e-19 - 3.689328161172122e-18im
                    1.0 + 3.689328161172121e-18im

"time = 2"

2-element Vector{Float64}:
 0.0013494068151740227
 0.998650593184826

2-element Vector{ComplexF64}:
 0.0016947512004967622 + 1.737411161600326e-16im
    0.9983052487995033 - 1.737411161600326e-16im

"time = 3"

2-element Vector{Float64}:
 0.0014262027025529831
 0.998573797297447

2-element Vector{ComplexF64}:
 0.0017782840256583144 + 7.580292267054115e-17im
    0.9982217159743417 - 7.580292267054113e-17im

"time = 4"

2-element Vector{Float64}:
 0.005055903542155723
 0.9949440964578443

2-element Vector{ComplexF64}:
 0.0059609803378120295 + 1.857293888817482e-16im
     0.994039019662188 - 1.8572938888174818e-16im

"time = 5"

2-element Vector{Float64}:
 0.002944637304520738
 0.9970553626954792

2-element Vector{ComplexF64}:
 0.003531275786109114 + 1.3565854412949296e-17im
   0.9964687242138908 - 1.3565854412949308e-17im

Indexed Edge 10 => 11 with index 34

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -5.156602899142233e-17 - 1.4972916581350413e-16im
                    1.0 + 1.4972916581350413e-16im

"time = 2"

2-element Vector{Float64}:
 0.0012583734121999815
 0.9987416265878

2-element Vector{ComplexF64}:
 0.0015806458452137379 - 1.756978870827766e-16im
    0.9984193541547863 + 1.7569788708277658e-16im

"time = 3"

2-element Vector{Float64}:
 0.001265554864304567
 0.9987344451356954

2-element Vector{ComplexF64}:
 0.00159051975766991 + 1.3230657111877661e-16im
    0.99840948024233 - 1.3230657111877666e-16im

"time = 4"

2-element Vector{Float64}:
 0.0012854558636805665
 0.9987145441363194

2-element Vector{ComplexF64}:
 0.0016194470337534523 + 4.976140267332619e-16im
    0.9983805529662465 - 4.97614026733262e-16im

"time = 5"

2-element Vector{Float64}:
 0.0012971357497809936
 0.998702864250219

2-element Vector{ComplexF64}:
 0.001633153327117348 - 8.909887953908599e-17im
   0.9983668466728827 + 8.909887953908598e-17im

Indexed Edge 10 => 12 with index 35

"time = 1"

2-element Vector{Float64}:
 4.26139216208893e-20
 1.0

2-element Vector{ComplexF64}:
 2.3684657581699766e-18 - 6.212496309115914e-19im
                    1.0 + 6.212496309116558e-19im

"time = 2"

2-element Vector{Float64}:
 0.0013502468006072626
 0.9986497531993928

2-element Vector{ComplexF64}:
 0.0016958046597110375 + 1.948740944721145e-17im
    0.9983041953402889 - 1.9487409447211527e-17im

"time = 3"

2-element Vector{Float64}:
 0.0014228891771519525
 0.9985771108228481

2-element Vector{ComplexF64}:
 0.0017745825613080133 + 9.968471014255674e-18im
    0.9982254174386921 - 9.968471014255631e-18im

"time = 4"

2-element Vector{Float64}:
 0.005054736986362189
 0.9949452630136378

2-element Vector{ComplexF64}:
 0.005960326284198718 + 4.91133414908839e-16im
   0.9940396737158013 - 4.911334149088388e-16im

"time = 5"

2-element Vector{Float64}:
 0.002930635807815948
 0.9970693641921841

2-element Vector{ComplexF64}:
 0.0035158080405965535 + 2.2138298179342864e-16im
    0.9964841919594034 - 2.213829817934287e-16im

Indexed Edge 10 => 20 with index 36

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -7.005406962026174e-17 + 1.3565425705684365e-17im
                    1.0 - 1.3565425705684315e-17im

"time = 2"

2-element Vector{Float64}:
 0.001349407802358577
 0.9986505921976415

2-element Vector{ComplexF64}:
 0.0016947512618789016 + 1.0453196833930958e-16im
    0.9983052487381211 - 1.0453196833930956e-16im

"time = 3"

2-element Vector{Float64}:
 0.0014265232621947924
 0.9985734767378052

2-element Vector{ComplexF64}:
 0.0017790890042422287 - 1.5226733671104082e-17im
    0.9982209109957577 + 1.5226733671104107e-17im

"time = 4"

2-element Vector{Float64}:
 0.005056335443870518
 0.9949436645561295

2-element Vector{ComplexF64}:
 0.005962106791978619 + 1.4310654837568092e-16im
   0.9940378932080215 - 1.4310654837568094e-16im

"time = 5"

2-element Vector{Float64}:
 0.002944140040769847
 0.9970558599592302

2-element Vector{ComplexF64}:
 0.0035312356417301544 - 7.412204961833346e-17im
    0.9964687643582698 + 7.412204961833345e-17im

Indexed Edge 11 => 10 with index 37

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.5724281354871206e-16 + 4.828630630289589e-17im
     0.9999999999999999 - 4.828630630289587e-17im

"time = 2"

2-element Vector{Float64}:
 0.05232578507723179
 0.9476742149227682

2-element Vector{ComplexF64}:
 0.054146453758789466 - 4.609791877229654e-17im
   0.9458535462412105 + 4.60979187722965e-17im

"time = 3"

2-element Vector{Float64}:
 0.0693256284892578
 0.9306743715107422

2-element Vector{ComplexF64}:
 0.07143887705552057 - 7.231248662762503e-17im
  0.9285611229444793 + 7.231248662762502e-17im

"time = 4"

2-element Vector{Float64}:
 0.07779122987662371
 0.9222087701233763

2-element Vector{ComplexF64}:
 0.08012557351011713 - 7.46475416147802e-18im
  0.9198744264898828 + 7.464754161478026e-18im

"time = 5"

2-element Vector{Float64}:
 0.09074447591414987
 0.9092555240858502

2-element Vector{ComplexF64}:
 0.09315511627794179 - 2.9428382877854506e-17im
  0.9068448837220581 + 2.9428382877854506e-17im

Indexed Edge 11 => 17 with index 38

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 2.160895855080439e-17 + 1.5796012900234507e-16im
    0.9999999999999999 - 1.5796012900234515e-16im

"time = 2"

2-element Vector{Float64}:
 0.0608376828586832
 0.9391623171413168

2-element Vector{ComplexF64}:
 0.0629344891689457 - 4.002716533578783e-18im
 0.9370655108310543 + 4.002716533578731e-18im

"time = 3"

2-element Vector{Float64}:
 0.0608581348466563
 0.9391418651533437

2-element Vector{ComplexF64}:
 0.0629598962308083 + 8.71460586175444e-19im
 0.9370401037691917 - 8.714605861755741e-19im

"time = 4"

2-element Vector{Float64}:
 0.06092669179232988
 0.9390733082076701

2-element Vector{ComplexF64}:
 0.06304773715806565 + 1.552834079088868e-16im
  0.9369522628419343 - 1.5528340790888658e-16im

"time = 5"

2-element Vector{Float64}:
 0.06093004029395709
 0.9390699597060429

2-element Vector{ComplexF64}:
 0.0630517996552096 + 4.0518683397992935e-16im
 0.9369482003447905 - 4.0518683397992935e-16im

Indexed Edge 11 => 20 with index 39

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.2562814568820965e-16 + 1.8706996711916996e-16im
                     1.0 - 1.8706996711916996e-16im

"time = 2"

2-element Vector{Float64}:
 0.052326493998996346
 0.9476735060010036

2-element Vector{ComplexF64}:
 0.05414724148240937 + 2.2860997554179764e-17im
  0.9458527585175907 - 2.2860997554179737e-17im

"time = 3"

2-element Vector{Float64}:
 0.06934677878707479
 0.9306532212129253

2-element Vector{ComplexF64}:
 0.07146557101774854 - 2.6008093370486883e-16im
  0.9285344289822515 + 2.6008093370486873e-16im

"time = 4"

2-element Vector{Float64}:
 0.07786415638990472
 0.9221358436100953

2-element Vector{ComplexF64}:
 0.08022000844450083 + 1.3712540023422987e-16im
  0.9197799915554993 - 1.3712540023422982e-16im

"time = 5"

2-element Vector{Float64}:
 0.09081363330693625
 0.9091863666930637

2-element Vector{ComplexF64}:
 0.09324585700268828 + 3.790278031926357e-16im
  0.9067541429973117 - 3.790278031926357e-16im

Indexed Edge 12 => 6 with index 40

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -7.535545274130383e-18 + 1.623972662610044e-16im
                    1.0 - 1.6239726626100445e-16im

"time = 2"

2-element Vector{Float64}:
 0.00017488871072994348
 0.9998251112892701

2-element Vector{ComplexF64}:
 0.00026184223609908845 - 9.951616161794823e-17im
      0.999738157763901 + 9.951616161794827e-17im

"time = 3"

2-element Vector{Float64}:
 0.00017704767624656238
 0.9998229523237534

2-element Vector{ComplexF64}:
 0.0002647239865663491 - 1.5933178160842935e-16im
    0.9997352760134337 + 1.5933178160842932e-16im

"time = 4"

2-element Vector{Float64}:
 0.00019275463687973865
 0.9998072453631203

2-element Vector{ComplexF64}:
 0.0002872048844513307 + 1.8974388511515465e-16im
    0.9997127951155487 - 1.8974388511515463e-16im

"time = 5"

2-element Vector{Float64}:
 0.00021140425958860224
 0.9997885957404115

2-element Vector{ComplexF64}:
 0.00031551241441674435 - 4.643870853296076e-16im
     0.9996844875855831 + 4.643870853296075e-16im

Indexed Edge 12 => 10 with index 41

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 4.7813272724489343e-17 + 1.5045346223400099e-16im
                    1.0 - 1.5045346223400084e-16im

"time = 2"

2-element Vector{Float64}:
 0.00017487272570495171
 0.9998251272742951

2-element Vector{ComplexF64}:
 0.00026181203925920444 - 1.170562223892386e-16im
     0.9997381879607409 + 1.170562223892387e-16im

"time = 3"

2-element Vector{Float64}:
 0.00017666553017868492
 0.9998233344698213

2-element Vector{ComplexF64}:
 0.00026410099728473577 - 1.675895437817885e-16im
     0.9997358990027152 + 1.675895437817886e-16im

"time = 4"

2-element Vector{Float64}:
 0.00019230647781067107
 0.9998076935221892

2-element Vector{ComplexF64}:
 0.00028647015892408574 - 3.2815263309909254e-17im
      0.999713529841076 + 3.2815263309909346e-17im

"time = 5"

2-element Vector{Float64}:
 0.00020962762323809564
 0.9997903723767618

2-element Vector{ComplexF64}:
 0.0003123901084124433 - 1.3713966693389282e-17im
    0.9996876098915877 + 1.371396669338946e-17im

Indexed Edge 12 => 14 with index 42

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.3872584928408188e-16 + 7.424364680667638e-17im
                     1.0 - 7.424364680667625e-17im

"time = 2"

2-element Vector{Float64}:
 0.00017023066274903287
 0.999829769337251

2-element Vector{ComplexF64}:
 0.0002548674912443959 - 4.6610546089602836e-17im
    0.9997451325087556 + 4.6610546089602885e-17im

"time = 3"

2-element Vector{Float64}:
 0.00017433609582703232
 0.9998256639041729

2-element Vector{ComplexF64}:
 0.00026099661417138426 - 2.1301396368242183e-17im
     0.9997390033858286 + 2.130139636824201e-17im

"time = 4"

2-element Vector{Float64}:
 0.00017653368285598458
 0.999823466317144

2-element Vector{ComplexF64}:
 0.0002641748516605464 - 8.50216015178403e-16im
    0.9997358251483394 + 8.502160151784028e-16im

"time = 5"

2-element Vector{Float64}:
 0.0001793265122668319
 0.9998206734877332

2-element Vector{ComplexF64}:
 0.0002687099479251775 - 2.806012541574192e-17im
     0.999731290052075 + 2.806012541574195e-17im

Indexed Edge 12 => 16 with index 43

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 7.867578191139422e-18 + 1.7461571235761207e-17im
                   1.0 - 1.7461571235761198e-17im

"time = 2"

2-element Vector{Float64}:
 0.00017488005240917504
 0.9998251199475908

2-element Vector{ComplexF64}:
 0.0002618278552080856 - 9.909949919267306e-17im
     0.999738172144792 + 9.909949919267348e-17im

"time = 3"

2-element Vector{Float64}:
 0.0001771039668667056
 0.9998228960331333

2-element Vector{ComplexF64}:
 0.00026488455119793214 - 2.361696981038795e-16im
      0.999735115448802 + 2.361696981038794e-16im

"time = 4"

2-element Vector{Float64}:
 0.00019279347815442496
 0.9998072065218455

2-element Vector{ComplexF64}:
 0.0002873420111053446 - 5.24839416766164e-16im
    0.9997126579888945 + 5.24839416766164e-16im

"time = 5"

2-element Vector{Float64}:
 0.00021148237549441004
 0.9997885176245055

2-element Vector{ComplexF64}:
 0.0003156783346187263 - 1.6137656555959628e-16im
    0.9996843216653813 + 1.6137656555959638e-16im

Indexed Edge 12 => 19 with index 44

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.3620086308018986e-16 + 7.933627479066344e-17im
      1.0000000000000002 - 7.933627479066345e-17im

"time = 2"

2-element Vector{Float64}:
 0.00017544945034975718
 0.9998245505496502

2-element Vector{ComplexF64}:
 0.00026268014240839025 - 1.7141393801489914e-16im
     0.9997373198575915 + 1.7141393801489912e-16im

"time = 3"

2-element Vector{Float64}:
 0.00017406721701707984
 0.9998259327829829

2-element Vector{ComplexF64}:
 0.00026056559614626867 - 4.2979954290951903e-16im
     0.9997394344038538 + 4.297995429095189e-16im

"time = 4"

2-element Vector{Float64}:
 0.0001873013746159048
 0.999812698625384

2-element Vector{ComplexF64}:
 0.00027957920326345225 + 8.343658860696224e-17im
     0.9997204207967365 - 8.343658860696243e-17im

"time = 5"

2-element Vector{Float64}:
 0.00020739435145320385
 0.9997926056485469

2-element Vector{ComplexF64}:
 0.00030878506840167306 - 2.527460688460731e-16im
     0.9996912149315984 + 2.5274606884607343e-16im

Indexed Edge 12 => 20 with index 45

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.4904164591120268e-16 - 5.021465791059733e-17im
     0.9999999999999998 + 5.021465791059749e-17im

"time = 2"

2-element Vector{Float64}:
 0.00017488691564826797
 0.9998251130843517

2-element Vector{ComplexF64}:
 0.0002618381298896204 - 1.5696867951988854e-16im
    0.9997381618701104 + 1.569686795198885e-16im

"time = 3"

2-element Vector{Float64}:
 0.00017709551066520486
 0.9998229044893348

2-element Vector{ComplexF64}:
 0.00026487255962471585 + 1.6906307714229422e-16im
     0.9997351274403752 - 1.690630771422941e-16im

"time = 4"

2-element Vector{Float64}:
 0.00019279274379448608
 0.9998072072562054

2-element Vector{ComplexF64}:
 0.00028734103834610454 - 1.5953064215975545e-16im
      0.999712658961654 + 1.5953064215975557e-16im

"time = 5"

2-element Vector{Float64}:
 0.00021145362087160286
 0.9997885463791284

2-element Vector{ComplexF64}:
 0.0003156351416814332 - 1.82841353317889e-16im
    0.9996843648583185 + 1.8284135331788885e-16im

Indexed Edge 13 => 16 with index 46

"time = 1"

2-element Vector{Float64}:
 1.1891229846364983e-17
 1.0

2-element Vector{ComplexF64}:
 1.279531428878262e-32 - 1.5910738166749782e-33im
                   1.0 + 2.0358686031456502e-33im

"time = 2"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
  0.5000000000000001 - 5.421010862427533e-18im
 0.49999999999999994 + 5.421010862427533e-18im

"time = 3"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
 0.49999999999999994 - 5.8966280726613325e-18im
 0.49999999999999994 + 5.8966280726613325e-18im

"time = 4"

2-element Vector{Float64}:
 0.5
 0.5

2-element Vector{ComplexF64}:
                0.5 - 5.952512907192562e-18im
 0.4999999999999999 + 5.952512907192562e-18im

"time = 5"

2-element Vector{Float64}:
 0.5000000000000001
 0.4999999999999999

2-element Vector{ComplexF64}:
 0.5000000000000001 - 1.1651910620020017e-17im
 0.4999999999999999 + 1.1651910620020017e-17im

Indexed Edge 14 => 3 with index 47

"time = 1"

2-element Vector{Float64}:
 2.377592572687958e-19
 1.0

2-element Vector{ComplexF64}:
 -4.645259311524166e-18 - 1.0213822107461483e-17im
                    1.0 + 1.0213822107461497e-17im

"time = 2"

2-element Vector{Float64}:
 0.009223530020519038
 0.990776469979481

2-element Vector{ComplexF64}:
 0.010322201036044584 + 1.1535235962113341e-16im
   0.9896777989639555 - 1.1535235962113356e-16im

"time = 3"

2-element Vector{Float64}:
 0.009245419384199552
 0.9907545806158005

2-element Vector{ComplexF64}:
 0.010336907927810723 - 1.148192292748105e-16im
   0.9896630920721893 + 1.1481922927481067e-16im

"time = 4"

2-element Vector{Float64}:
 0.00933777145598133
 0.9906622285440188

2-element Vector{ComplexF64}:
 0.010437835329830529 + 7.817313096646714e-17im
   0.9895621646701694 - 7.81731309664671e-17im

"time = 5"

2-element Vector{Float64}:
 0.009490124308374709
 0.9905098756916253

2-element Vector{ComplexF64}:
 0.01059256486296586 + 3.546858468091456e-16im
  0.9894074351370341 - 3.546858468091456e-16im

Indexed Edge 14 => 12 with index 48

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -4.051289985502057e-18 + 1.6104773288157543e-16im
                    1.0 - 1.6104773288157524e-16im

"time = 2"

2-element Vector{Float64}:
 0.009221061167828098
 0.9907789388321718

2-element Vector{ComplexF64}:
 0.010318866728550567 + 2.411868314119064e-16im
   0.9896811332714495 - 2.411868314119064e-16im

"time = 3"

2-element Vector{Float64}:
 0.00925536890924869
 0.9907446310907513

2-element Vector{ComplexF64}:
 0.010348315779441527 + 1.0946294987182266e-16im
   0.9896516842205584 - 1.0946294987182255e-16im

"time = 4"

2-element Vector{Float64}:
 0.009366622024619319
 0.9906333779753808

2-element Vector{ComplexF64}:
 0.010473804726014876 + 2.3867143673521984e-16im
   0.9895261952739851 - 2.386714367352203e-16im

"time = 5"

2-element Vector{Float64}:
 0.00952433589167774
 0.9904756641083222

2-element Vector{ComplexF64}:
 0.010635269420904514 + 4.025858557307545e-16im
   0.9893647305790955 - 4.0258585573075455e-16im

Indexed Edge 14 => 15 with index 49

"time = 1"

2-element Vector{Float64}:
 -2.822222061752155e-19
  1.0

2-element Vector{ComplexF64}:
 1.3741967186072298e-16 + 8.902882053000058e-17im
     0.9999999999999999 - 8.90288205300008e-17im

"time = 2"

2-element Vector{Float64}:
 0.009158309879600769
 0.9908416901203991

2-element Vector{ComplexF64}:
 0.010248730244951914 + 1.3274488651448398e-16im
    0.989751269755048 - 1.3274488651448383e-16im

"time = 3"

2-element Vector{Float64}:
 0.009174088303438358
 0.9908259116965616

2-element Vector{ComplexF64}:
 0.01026985826414668 + 2.670508513985622e-16im
  0.9897301417358534 - 2.6705085139856195e-16im

"time = 4"

2-element Vector{Float64}:
 0.009194868467375706
 0.9908051315326243

2-element Vector{ComplexF64}:
 0.01029728988525547 + 2.0266607766537709e-16im
  0.9897027101147444 - 2.0266607766537667e-16im

"time = 5"

2-element Vector{Float64}:
 0.009203790221278365
 0.9907962097787216

2-element Vector{ComplexF64}:
 0.010307758034237686 + 4.2077329977619383e-16im
   0.9896922419657623 - 4.207732997761933e-16im

Indexed Edge 14 => 20 with index 50

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -2.6580024351501313e-17 + 2.4338650596629654e-17im
                     1.0 - 2.433865059662999e-17im

"time = 2"

2-element Vector{Float64}:
 0.009221112084486885
 0.9907788879155132

2-element Vector{ComplexF64}:
 0.010318923632602938 - 6.016439997478389e-17im
   0.9896810763673971 + 6.01643999747831e-17im

"time = 3"

2-element Vector{Float64}:
 0.009256638228306321
 0.9907433617716936

2-element Vector{ComplexF64}:
 0.010351097089974943 + 5.436801853749951e-16im
   0.9896489029100252 - 5.436801853749952e-16im

"time = 4"

2-element Vector{Float64}:
 0.009368158015947295
 0.9906318419840526

2-element Vector{ComplexF64}:
 0.01047736670317459 + 9.359840572509175e-17im
  0.9895226332968254 - 9.359840572509265e-17im

"time = 5"

2-element Vector{Float64}:
 0.009522284146258518
 0.9904777158537416

2-element Vector{ComplexF64}:
 0.010635153795003413 + 5.2541249423136517e-17im
   0.9893648462049967 - 5.254124942313715e-17im

Indexed Edge 15 => 4 with index 51

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.4319420552948085e-16 + 8.850680826305207e-17im
                     1.0 - 8.850680826305364e-17im

"time = 2"

2-element Vector{Float64}:
 0.009160999106299923
 0.9908390008937

2-element Vector{ComplexF64}:
 0.010252256036294902 - 2.138667341423645e-16im
    0.989747743963705 + 2.138667341423647e-16im

"time = 3"

2-element Vector{Float64}:
 0.009246120912422667
 0.9907538790875773

2-element Vector{ComplexF64}:
 0.010349578366843462 + 1.426098427362793e-16im
   0.9896504216331564 - 1.426098427362805e-16im

"time = 4"

2-element Vector{Float64}:
 0.00928838489066532
 0.9907116151093346

2-element Vector{ComplexF64}:
 0.010402697284741448 - 1.246372835311912e-16im
   0.9895973027152586 + 1.246372835311912e-16im

"time = 5"

2-element Vector{Float64}:
 0.009292115241816444
 0.9907078847581836

2-element Vector{ComplexF64}:
 0.01040698425721113 + 1.0159643834824721e-17im
  0.9895930157427889 - 1.0159643834825347e-17im

Indexed Edge 15 => 6 with index 52

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.2622911234363383e-16 - 9.669324909369814e-17im
      1.0000000000000002 + 9.669324909369826e-17im

"time = 2"

2-element Vector{Float64}:
 0.009158268812156927
 0.9908417311878431

2-element Vector{ComplexF64}:
 0.010248747342608352 + 5.212615675341297e-17im
   0.9897512526573916 - 5.21261567534128e-17im

"time = 3"

2-element Vector{Float64}:
 0.009256191747719538
 0.9907438082522805

2-element Vector{ComplexF64}:
 0.0103611232783131 + 2.867665988040602e-16im
 0.9896388767216868 - 2.867665988040601e-16im

"time = 4"

2-element Vector{Float64}:
 0.009418377369951584
 0.9905816226300485

2-element Vector{ComplexF64}:
 0.01056495235873122 - 6.081305846763301e-18im
  0.9894350476412689 + 6.081305846763802e-18im

"time = 5"

2-element Vector{Float64}:
 0.009437464195210497
 0.9905625358047895

2-element Vector{ComplexF64}:
 0.01058733222157308 + 3.804780875873544e-16im
   0.989412667778427 - 3.8047808758735453e-16im

Indexed Edge 15 => 14 with index 53

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -4.032782605482623e-17 + 1.0838351512348822e-17im
     0.9999999999999999 - 1.0838351512349553e-17im

"time = 2"

2-element Vector{Float64}:
 0.009158190079310907
 0.9908418099206892

2-element Vector{ComplexF64}:
 0.010248617525860154 + 2.4761196855829175e-16im
     0.98975138247414 - 2.4761196855829244e-16im

"time = 3"

2-element Vector{Float64}:
 0.009174003609415834
 0.9908259963905842

2-element Vector{ComplexF64}:
 0.010269823865108768 + 3.688870765804535e-16im
   0.9897301761348912 - 3.688870765804536e-16im

"time = 4"

2-element Vector{Float64}:
 0.009295590642377862
 0.990704409357622

2-element Vector{ComplexF64}:
 0.010422923688392626 + 1.5863389073379626e-16im
   0.9895770763116073 - 1.586338907337964e-16im

"time = 5"

2-element Vector{Float64}:
 0.009314045777323471
 0.9906859542226766

2-element Vector{ComplexF64}:
 0.010444593219390293 - 3.1376603063110095e-16im
   0.9895554067806096 + 3.137660306311007e-16im

Indexed Edge 15 => 16 with index 54

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -4.9852686347419284e-18 - 3.2153926898672054e-18im
      0.9999999999999999 + 3.2153926898662475e-18im

"time = 2"

2-element Vector{Float64}:
 0.009157890015465034
 0.9908421099845349

2-element Vector{ComplexF64}:
 0.010248281312011004 + 1.8501757123361254e-16im
   0.9897517186879891 - 1.8501757123361254e-16im

"time = 3"

2-element Vector{Float64}:
 0.009257707076356753
 0.9907422929236432

2-element Vector{ComplexF64}:
 0.010364170338883628 - 2.6657305976950268e-17im
   0.9896358296611164 + 2.665730597694936e-17im

"time = 4"

2-element Vector{Float64}:
 0.009419922955475349
 0.9905800770445247

2-element Vector{ComplexF64}:
 0.010568498471160077 - 2.188056120821798e-16im
     0.98943150152884 + 2.1880561208218046e-16im

"time = 5"

2-element Vector{Float64}:
 0.00943686052310854
 0.9905631394768915

2-element Vector{ComplexF64}:
 0.010588927058017075 - 9.616016313264636e-17im
   0.9894110729419829 + 9.616016313264574e-17im

Indexed Edge 16 => 3 with index 55

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 3.707317618170808e-17 - 2.528520980828644e-17im
                   1.0 + 2.5285209808286607e-17im

"time = 2"

2-element Vector{Float64}:
 3.1457358181529317e-6
 0.9999968542641818

2-element Vector{ComplexF64}:
 0.0015067644136290228 - 1.1214209596247896e-16im
    0.9984932355863712 + 1.1214209596248061e-16im

"time = 3"

2-element Vector{Float64}:
 3.0421414591016085e-5
 0.999969578585409

2-element Vector{ComplexF64}:
 0.0013810589041956234 - 5.706533474404106e-16im
    0.9986189410958044 + 5.706533474404104e-16im

"time = 4"

2-element Vector{Float64}:
 3.467386132180677e-5
 0.9999653261386782

2-element Vector{ComplexF64}:
 0.0014011426775168328 - 2.0202712650184372e-16im
    0.9985988573224832 + 2.020271265018437e-16im

"time = 5"

2-element Vector{Float64}:
 2.8791208258369638e-5
 0.9999712087917417

2-element Vector{ComplexF64}:
 0.0013917724334863454 - 9.324876787141109e-16im
    0.9986082275665136 + 9.324876787141097e-16im

Indexed Edge 16 => 4 with index 56

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.1667960959110699e-17 + 9.126145677701351e-18im
                    1.0 - 9.126145677700385e-18im

"time = 2"

2-element Vector{Float64}:
 3.1451402786224675e-6
 0.9999968548597213

2-element Vector{ComplexF64}:
 0.0015064980222462266 - 2.7369464172490296e-16im
    0.9984935019777537 + 2.7369464172490183e-16im

"time = 3"

2-element Vector{Float64}:
 3.0417760048231034e-5
 0.9999695822399518

2-element Vector{ComplexF64}:
 0.0013808454786714117 - 2.1532964208755717e-16im
    0.9986191545213287 + 2.1532964208755766e-16im

"time = 4"

2-element Vector{Float64}:
 3.4205674733190986e-5
 0.9999657943252668

2-element Vector{ComplexF64}:
 0.0013988677580860152 + 7.249333462711992e-17im
     0.998601132241914 - 7.249333462711902e-17im

"time = 5"

2-element Vector{Float64}:
 2.9060020600157793e-5
 0.9999709399793998

2-element Vector{ComplexF64}:
 0.0013907298103321979 - 7.373276904390822e-16im
    0.9986092701896678 + 7.373276904390808e-16im

Indexed Edge 16 => 8 with index 57

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 2.5427939035743363e-17 + 2.6666479978387756e-17im
                    1.0 - 2.6666479978386986e-17im

"time = 2"

2-element Vector{Float64}:
 3.143528773987364e-6
 0.999996856471226

2-element Vector{ComplexF64}:
 0.0015057085375568089 - 1.0200269833993504e-16im
    0.9984942914624432 + 1.020026983399336e-16im

"time = 3"

2-element Vector{Float64}:
 2.7158071764147627e-5
 0.9999728419282359

2-element Vector{ComplexF64}:
 0.0013769612555893961 - 2.0500116569121737e-16im
    0.9986230387444106 + 2.0500116569121905e-16im

"time = 4"

2-element Vector{Float64}:
 3.111316045461479e-5
 0.9999688868395453

2-element Vector{ComplexF64}:
 0.001386664418955807 - 5.869013700341807e-17im
   0.9986133355810441 + 5.869013700341773e-17im

"time = 5"

2-element Vector{Float64}:
 2.539050035497941e-5
 0.999974609499645

2-element Vector{ComplexF64}:
 0.0013776180301594057 - 7.501408647524956e-16im
    0.9986223819698405 + 7.501408647524936e-16im

Indexed Edge 16 => 9 with index 58

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.5355870045788237e-16 + 3.0823762780057184e-17im
                     1.0 - 3.0823762780056926e-17im

"time = 2"

2-element Vector{Float64}:
 3.144503931679627e-6
 0.9999968554960683

2-element Vector{ComplexF64}:
 0.0015060153660819144 - 2.5572269385196422e-17im
    0.9984939846339181 + 2.557226938519718e-17im

"time = 3"

2-element Vector{Float64}:
 3.001028793171021e-5
 0.9999699897120683

2-element Vector{ComplexF64}:
 0.0013805259088310062 + 4.069301964856159e-17im
     0.998619474091169 - 4.069301964856242e-17im

"time = 4"

2-element Vector{Float64}:
 3.421691157174635e-5
 0.9999657830884283

2-element Vector{ComplexF64}:
 0.0013986452838199786 + 2.2065569129960523e-16im
    0.9986013547161802 - 2.2065569129960452e-16im

"time = 5"

2-element Vector{Float64}:
 2.730410494113951e-5
 0.9999726958950589

2-element Vector{ComplexF64}:
 0.0013877711836814877 - 5.434550265476707e-16im
    0.9986122288163185 + 5.434550265476707e-16im

Indexed Edge 16 => 12 with index 59

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.518667551441043e-16 + 4.616809932779555e-17im
                    1.0 - 4.616809932779537e-17im

"time = 2"

2-element Vector{Float64}:
 3.144761149058799e-6
 0.999996855238851

2-element Vector{ComplexF64}:
 0.0015061241561617241 - 2.382104195760002e-16im
    0.9984938758438382 + 2.382104195760007e-16im

"time = 3"

2-element Vector{Float64}:
 3.0475631899211025e-5
 0.9999695243681008

2-element Vector{ComplexF64}:
 0.0013811879258670415 + 2.8927053518474976e-16im
     0.998618812074133 - 2.8927053518475075e-16im

"time = 4"

2-element Vector{Float64}:
 3.4796299874633273e-5
 0.9999652037001254

2-element Vector{ComplexF64}:
 0.0014018819059000026 + 7.657209810203234e-16im
    0.9985981180940999 - 7.657209810203226e-16im

"time = 5"

2-element Vector{Float64}:
 2.727869119329068e-5
 0.9999727213088068

2-element Vector{ComplexF64}:
 0.0013900577985862031 - 3.961445385269711e-16im
    0.9986099422014139 + 3.9614453852697155e-16im

Indexed Edge 16 => 13 with index 60

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 7.686761799575553e-17 - 1.3966410537356896e-16im
                   1.0 + 1.3966410537356753e-16im

"time = 2"

2-element Vector{Float64}:
 3.1255305945366544e-6
 0.9999968744694054

2-element Vector{ComplexF64}:
 0.0014973617602500168 - 7.745394868490337e-17im
    0.9985026382397499 + 7.745394868490528e-17im

"time = 3"

2-element Vector{Float64}:
 4.1627276289912325e-6
 0.9999958372723711

2-element Vector{ComplexF64}:
 0.0014944812901717924 + 4.3044265322931316e-16im
    0.9985055187098282 - 4.304426532293128e-16im

"time = 4"

2-element Vector{Float64}:
 4.7765100631467625e-6
 0.9999952234899369

2-element Vector{ComplexF64}:
 0.0014906199396885883 + 6.673749856740916e-16im
    0.9985093800603114 - 6.673749856740896e-16im

"time = 5"

2-element Vector{Float64}:
 -4.546139860325119e-6
  1.0000045461398603

2-element Vector{ComplexF64}:
 0.0014735426853859093 - 5.857442284123236e-16im
    0.9985264573146141 + 5.857442284123219e-16im

Indexed Edge 16 => 15 with index 61

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.562825628298663e-16 + 1.108702901458321e-17im
                   1.0 - 1.1087029014582337e-17im

"time = 2"

2-element Vector{Float64}:
 3.143417892442778e-6
 0.9999968565821076

2-element Vector{ComplexF64}:
 0.001503992413963482 - 7.658718868602186e-17im
   0.9984960075860365 + 7.658718868602211e-17im

"time = 3"

2-element Vector{Float64}:
 2.994437677087992e-5
 0.999970055623229

2-element Vector{ComplexF64}:
 0.0013819130121872408 + 4.91099598312726e-16im
    0.9986180869878127 - 4.910995983127259e-16im

"time = 4"

2-element Vector{Float64}:
 3.4253184644704764e-5
 0.9999657468153552

2-element Vector{ComplexF64}:
 0.001398646315846458 + 3.6208610938890335e-17im
   0.9986013536841535 - 3.620861093889117e-17im

"time = 5"

2-element Vector{Float64}:
 2.3493262409655525e-5
 0.9999765067375903

2-element Vector{ComplexF64}:
 0.00137991616042232 - 5.602009409443965e-16im
  0.9986200838395777 + 5.602009409443962e-16im

Indexed Edge 16 => 18 with index 62

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 2.4363118457241836e-18 + 2.000335159668132e-18im
                    1.0 - 2.0003351596675822e-18im

"time = 2"

2-element Vector{Float64}:
 3.1259974811210506e-6
 0.9999968740025189

2-element Vector{ComplexF64}:
 0.0014975217094792363 - 1.4203376867356017e-16im
    0.9985024782905206 + 1.420337686735592e-16im

"time = 3"

2-element Vector{Float64}:
 2.7052588253689058e-5
 0.9999729474117462

2-element Vector{ComplexF64}:
 0.0013759170942885042 + 3.1399848395637947e-16im
    0.9986240829057116 - 3.1399848395637923e-16im

"time = 4"

2-element Vector{Float64}:
 2.7773991191855508e-5
 0.9999722260088082

2-element Vector{ComplexF64}:
 0.0013824862624040762 + 5.926936193281078e-16im
    0.9986175137375958 - 5.926936193281096e-16im

"time = 5"

2-element Vector{Float64}:
 2.7715945837672017e-5
 0.9999722840541624

2-element Vector{ComplexF64}:
 0.001381788668188852 - 4.855761488032471e-16im
   0.9986182113318112 + 4.855761488032456e-16im

Indexed Edge 17 => 11 with index 63

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -7.99548734614122e-18 - 4.780555058743961e-18im
                   1.0 + 4.780555058743957e-18im

"time = 2"

2-element Vector{Float64}:
 0.2585953913402141
 0.741404608659786

2-element Vector{ComplexF64}:
 0.25871856073176774 - 4.1097757939046036e-17im
  0.7412814392682323 + 4.1097757939046024e-17im

"time = 3"

2-element Vector{Float64}:
 0.25915852745618617
 0.7408414725438138

2-element Vector{ComplexF64}:
 0.2592817354480618 + 1.848305573224157e-16im
 0.7407182645519382 - 1.848305573224157e-16im

"time = 4"

2-element Vector{Float64}:
 0.26108339597017954
 0.7389166040298205

2-element Vector{ComplexF64}:
 0.261206546345533 - 6.053225085133984e-17im
 0.738793453654467 + 6.053225085133984e-17im

"time = 5"

2-element Vector{Float64}:
 0.26150764460582226
 0.7384923553941778

2-element Vector{ComplexF64}:
 0.26163075805960834 + 9.985347755024372e-17im
  0.7383692419403917 - 9.985347755024372e-17im

Indexed Edge 17 => 19 with index 64

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.1873738974933682e-17 - 8.434593569343535e-18im
                    1.0 + 8.434593569343572e-18im

"time = 2"

2-element Vector{Float64}:
 0.25899310495170597
 0.741006895048294

2-element Vector{ComplexF64}:
 0.2591163975539676 + 4.111432495148047e-17im
 0.7408836024460325 - 4.111432495148052e-17im

"time = 3"

2-element Vector{Float64}:
 0.26018494157381644
 0.7398150584261836

2-element Vector{ComplexF64}:
 0.26036969216752304 + 1.5094234273816748e-16im
   0.739630307832477 - 1.5094234273816777e-16im

"time = 4"

2-element Vector{Float64}:
 0.27476369095171066
 0.7252363090482894

2-element Vector{ComplexF64}:
 0.2754408657274474 + 1.3607864116124677e-17im
 0.7245591342725527 - 1.3607864116124627e-17im

"time = 5"

2-element Vector{Float64}:
 0.2748327456000656
 0.7251672543999343

2-element Vector{ComplexF64}:
 0.27551628094183295 - 1.4300000433563247e-16im
   0.724483719058167 + 1.4300000433563247e-16im

Indexed Edge 18 => 2 with index 65

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.6476280037592972e-17 + 1.2036438322319593e-17im
                    1.0 - 1.2036438322319531e-17im

"time = 2"

2-element Vector{Float64}:
 0.06083776044591813
 0.9391622395540818

2-element Vector{ComplexF64}:
 0.06293461330143484 + 2.712547771602375e-16im
  0.9370653866985653 - 2.712547771602368e-16im

"time = 3"

2-element Vector{Float64}:
 0.06873667557546186
 0.9312633244245381

2-element Vector{ComplexF64}:
 0.07155115038105338 - 3.7778972562664766e-16im
  0.9284488496189467 + 3.777897256266484e-16im

"time = 4"

2-element Vector{Float64}:
 0.0816169264457659
 0.9183830735542341

2-element Vector{ComplexF64}:
 0.08473161629901585 - 1.8054452556591081e-16im
  0.9152683837009842 + 1.8054452556590919e-16im

"time = 5"

2-element Vector{Float64}:
 0.08328947631687944
 0.9167105236831206

2-element Vector{ComplexF64}:
 0.08654730808501099 + 4.782367079954703e-16im
  0.9134526919149889 - 4.782367079954695e-16im

Indexed Edge 18 => 7 with index 66

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.4620760453100484e-16 - 1.090717371463571e-16im
                    1.0 + 1.0907173714635655e-16im

"time = 2"

2-element Vector{Float64}:
 0.06083776727088473
 0.9391622327291153

2-element Vector{ComplexF64}:
 0.06293441267673873 + 6.736274026709568e-18im
  0.9370655873232612 - 6.736274026711863e-18im

"time = 3"

2-element Vector{Float64}:
 0.06194505141659674
 0.9380549485834033

2-element Vector{ComplexF64}:
 0.06474552855949933 + 1.0775167303269698e-16im
  0.9352544714405006 - 1.0775167303269553e-16im

"time = 4"

2-element Vector{Float64}:
 0.06626040637305076
 0.9337395936269492

2-element Vector{ComplexF64}:
 0.06923052052947719 - 6.527023603467377e-17im
  0.9307694794705228 + 6.527023603467377e-17im

"time = 5"

2-element Vector{Float64}:
 0.06662843944485508
 0.9333715605551449

2-element Vector{ComplexF64}:
 0.06965525478737479 + 5.431521784759555e-16im
  0.9303447452126252 - 5.431521784759569e-16im

Indexed Edge 18 => 16 with index 67

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.506996844164198e-16 - 2.2439092477705402e-17im
                   1.0 + 2.2439092477705423e-17im

"time = 2"

2-element Vector{Float64}:
 0.060931886395756925
 0.939068113604243

2-element Vector{ComplexF64}:
 0.06303436026943718 + 1.0579733199923022e-16im
  0.9369656397305627 - 1.0579733199923022e-16im

"time = 3"

2-element Vector{Float64}:
 0.06987584669391356
 0.9301241533060864

2-element Vector{ComplexF64}:
 0.0720964615191488 - 2.3343428909202075e-16im
 0.9279035384808513 + 2.334342890920208e-16im

"time = 4"

2-element Vector{Float64}:
 0.08712572802654327
 0.9128742719734567

2-element Vector{ComplexF64}:
 0.08996855379078042 - 3.720181880744893e-18im
  0.9100314462092196 + 3.720181880744931e-18im

"time = 5"

2-element Vector{Float64}:
 0.08964367884820003
 0.9103563211518

2-element Vector{ComplexF64}:
 0.09252852158743491 + 2.1536730121084494e-16im
   0.907471478412565 - 2.1536730121084497e-16im

Indexed Edge 19 => 6 with index 68

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -8.736040642120008e-18 - 1.724176848760004e-16im
                    1.0 + 1.7241768487600048e-16im

"time = 2"

2-element Vector{Float64}:
 0.009160690197419167
 0.9908393098025808

2-element Vector{ComplexF64}:
 0.010251945902396446 - 1.440845777016609e-16im
   0.9897480540976037 + 1.440845777016609e-16im

"time = 3"

2-element Vector{Float64}:
 0.013656286983310294
 0.9863437130166898

2-element Vector{ComplexF64}:
 0.014810392430094728 + 9.199724267518696e-18im
   0.9851896075699054 - 9.199724267518725e-18im

"time = 4"

2-element Vector{Float64}:
 0.01505889293246938
 0.9849411070675307

2-element Vector{ComplexF64}:
 0.01635972666575944 + 2.6096849870160373e-16im
  0.9836402733342406 - 2.6096849870160373e-16im

"time = 5"

2-element Vector{Float64}:
 0.015854366381531995
 0.984145633618468

2-element Vector{ComplexF64}:
 0.017174024288621855 - 2.6374956024873433e-16im
   0.9828259757113781 + 2.637495602487344e-16im

Indexed Edge 19 => 12 with index 69

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.4597184451542096e-16 - 5.758142951317492e-17im
     0.9999999999999999 + 5.75814295131749e-17im

"time = 2"

2-element Vector{Float64}:
 0.009160615296988932
 0.990839384703011

2-element Vector{ComplexF64}:
 0.010251821763159214 + 9.853657138760041e-17im
   0.9897481782368408 - 9.853657138760039e-17im

"time = 3"

2-element Vector{Float64}:
 0.013656275156906
 0.9863437248430941

2-element Vector{ComplexF64}:
 0.01481036740610436 + 2.027429901921096e-16im
  0.9851896325938958 - 2.0274299019210962e-16im

"time = 4"

2-element Vector{Float64}:
 0.015058875315912075
 0.9849411246840879

2-element Vector{ComplexF64}:
 0.016359675866987153 + 4.693122693565469e-16im
   0.9836403241330129 - 4.693122693565469e-16im

"time = 5"

2-element Vector{Float64}:
 0.015854498751224664
 0.9841455012487753

2-element Vector{ComplexF64}:
 0.01717423122414042 - 1.8836365150700595e-16im
  0.9828257687758596 + 1.88363651507006e-16im

Indexed Edge 19 => 17 with index 70

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.2508017992539796e-16 + 1.0017382584711839e-16im
     0.9999999999999999 - 1.0017382584711838e-16im

"time = 2"

2-element Vector{Float64}:
 0.009160627034764127
 0.9908393729652358

2-element Vector{ComplexF64}:
 0.010251831965366043 + 4.888930529421441e-17im
    0.989748168034634 - 4.888930529421446e-17im

"time = 3"

2-element Vector{Float64}:
 0.009164189878823186
 0.9908358101211768

2-element Vector{ComplexF64}:
 0.010258569556280208 + 1.2135734118116143e-16im
   0.9897414304437198 - 1.213573411811615e-16im

"time = 4"

2-element Vector{Float64}:
 0.009166261051025734
 0.9908337389489743

2-element Vector{ComplexF64}:
 0.01026161369282514 + 4.610166915611288e-16im
  0.9897383863071749 - 4.610166915611287e-16im

"time = 5"

2-element Vector{Float64}:
 0.009170680578334462
 0.9908293194216655

2-element Vector{ComplexF64}:
 0.010266500404136993 - 1.2999733227192528e-16im
    0.989733499595863 + 1.2999733227192535e-16im

Indexed Edge 19 => 20 with index 71

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.0409501483139007e-17 - 1.0014852982321738e-17im
      0.9999999999999999 + 1.0014852982321825e-17im

"time = 2"

2-element Vector{Float64}:
 0.009160679467080409
 0.9908393205329197

2-element Vector{ComplexF64}:
 0.01025188638277859 + 3.125211175242428e-17im
  0.9897481136172214 - 3.125211175242433e-17im

"time = 3"

2-element Vector{Float64}:
 0.013657587215294432
 0.9863424127847056

2-element Vector{ComplexF64}:
 0.014813281931824704 - 3.6211061255713026e-16im
   0.9851867180681753 + 3.621106125571304e-16im

"time = 4"

2-element Vector{Float64}:
 0.015060670997203818
 0.9849393290027962

2-element Vector{ComplexF64}:
 0.016363725828859373 - 7.395189258595794e-17im
   0.9836362741711405 + 7.395189258595796e-17im

"time = 5"

2-element Vector{Float64}:
 0.015853241320104475
 0.9841467586798954

2-element Vector{ComplexF64}:
 0.01717463068845325 - 2.68207030002369e-16im
  0.9828253693115467 + 2.6820703000236897e-16im

Indexed Edge 20 => 2 with index 72

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 1.297170097005877e-16 - 8.902601020562271e-17im
                   1.0 + 8.902601020562333e-17im

"time = 2"

2-element Vector{Float64}:
 2.318534772533862e-5
 0.9999768146522747

2-element Vector{ComplexF64}:
 0.00019737779113049823 + 1.0798443843802952e-16im
     0.9998026222088696 - 1.0798443843802942e-16im

"time = 3"

2-element Vector{Float64}:
 5.154638980822649e-5
 0.9999484536101918

2-element Vector{ComplexF64}:
 0.00024618183848994224 + 6.010025796433712e-16im
       0.99975381816151 - 6.010025796433714e-16im

"time = 4"

2-element Vector{Float64}:
 6.011929991465666e-5
 0.9999398807000853

2-element Vector{ComplexF64}:
 0.0002612377107315896 + 1.46958058495664e-16im
    0.9997387622892685 - 1.4695805849566378e-16im

"time = 5"

2-element Vector{Float64}:
 -8.599693759003181e-5
  1.0000859969375901

2-element Vector{ComplexF64}:
 5.9098381566796404e-5 + 4.5790504106493585e-17im
    0.9999409016184333 - 4.579050410649336e-17im

Indexed Edge 20 => 7 with index 73

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -6.805044837915031e-17 + 1.4504273780341507e-16im
     1.0000000000000002 - 1.4504273780341418e-16im

"time = 2"

2-element Vector{Float64}:
 2.316237947003769e-5
 0.99997683762053

2-element Vector{ComplexF64}:
 0.00019718581919005295 + 1.3828528457181824e-16im
       0.99980281418081 - 1.382852845718175e-16im

"time = 3"

2-element Vector{Float64}:
 3.010566616603338e-5
 0.999969894333834

2-element Vector{ComplexF64}:
 0.00020965810032003295 + 4.658890544722911e-16im
     0.9997903418996801 - 4.658890544722913e-16im

"time = 4"

2-element Vector{Float64}:
 3.758364743710913e-5
 0.9999624163525629

2-element Vector{ComplexF64}:
 0.00022291094253137764 + 1.5776297434957085e-16im
     0.9997770890574685 - 1.577629743495704e-16im

"time = 5"

2-element Vector{Float64}:
 -3.8801780003583224e-5
  1.0000388017800037

2-element Vector{ComplexF64}:
 0.0001147884178511313 - 2.401419779450112e-17im
    0.9998852115821489 + 2.401419779450168e-17im

Indexed Edge 20 => 10 with index 74

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.026651387501848e-16 - 1.193753333467201e-16im
     1.0000000000000002 + 1.1937533334671945e-16im

"time = 2"

2-element Vector{Float64}:
 2.3162090166929105e-5
 0.9999768379098332

2-element Vector{ComplexF64}:
 0.00019717158136284168 + 2.7487695648624313e-16im
     0.9998028284186372 - 2.748769564862435e-16im

"time = 3"

2-element Vector{Float64}:
 5.684691407221881e-5
 0.9999431530859277

2-element Vector{ComplexF64}:
 0.00025582948069693826 + 8.594543908184773e-16im
     0.9997441705193032 - 8.59454390818476e-16im

"time = 4"

2-element Vector{Float64}:
 7.31577110353217e-5
 0.9999268422889647

2-element Vector{ComplexF64}:
 0.0002838143570694208 - 3.1434487476839794e-16im
    0.9997161856429304 + 3.143448747683981e-16im

"time = 5"

2-element Vector{Float64}:
 -0.000337062776199521
  1.0003370627761996

2-element Vector{ComplexF64}:
 -0.00024712405051460003 + 9.499577785509675e-17im
      1.0002471240505146 - 9.499577785509723e-17im

Indexed Edge 20 => 11 with index 75

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.1456586112793552e-16 - 1.0648375106159709e-16im
      1.0000000000000002 + 1.06483751061597e-16im

"time = 2"

2-element Vector{Float64}:
 2.3096692187349705e-5
 0.9999769033078127

2-element Vector{ComplexF64}:
 0.00019659840567664086 + 3.7033303376855706e-16im
     0.9998034015943233 - 3.703330337685574e-16im

"time = 3"

2-element Vector{Float64}:
 5.22055859739459e-5
 0.999947794414026

2-element Vector{ComplexF64}:
 0.0002477141109423893 + 1.883527256583178e-16im
    0.9997522858890575 - 1.883527256583173e-16im

"time = 4"

2-element Vector{Float64}:
 6.11028816442759e-5
 0.9999388971183557

2-element Vector{ComplexF64}:
 0.00026289953159940054 - 3.792972208420847e-17im
     0.9997371004684007 + 3.792972208420885e-17im

"time = 5"

2-element Vector{Float64}:
 -0.0001277865125813731
  1.0001277865125815

2-element Vector{ComplexF64}:
 2.9200215550532398e-6 + 3.817496435719325e-16im
    0.9999970799784449 - 3.817496435719325e-16im

Indexed Edge 20 => 12 with index 76

"time = 1"

2-element Vector{Float64}:
 -6.986437400247281e-22
  1.0

2-element Vector{ComplexF64}:
 -1.1667378362245661e-16 + 1.0743591680128774e-16im
      1.0000000000000002 - 1.0743591680128737e-16im

"time = 2"

2-element Vector{Float64}:
 2.3164711822769267e-5
 0.9999768352881773

2-element Vector{ComplexF64}:
 0.00019719423636903552 - 1.2164684283939479e-17im
      0.999802805763631 + 1.2164684283940146e-17im

"time = 3"

2-element Vector{Float64}:
 5.694588369881402e-5
 0.9999430541163011

2-element Vector{ComplexF64}:
 0.0002560202168188386 + 2.0243336738883732e-16im
    0.9997439797831811 - 2.0243336738883777e-16im

"time = 4"

2-element Vector{Float64}:
 7.329949607857768e-5
 0.9999267005039214

2-element Vector{ComplexF64}:
 0.00028411692197810937 - 2.336509356650591e-16im
      0.999715883078022 + 2.3365093566505805e-16im

"time = 5"

2-element Vector{Float64}:
 -0.0003582988269909218
  1.000358298826991

2-element Vector{ComplexF64}:
 -0.00026721580937140064 + 1.8084184634570947e-16im
      1.0002672158093713 - 1.8084184634571006e-16im

Indexed Edge 20 => 14 with index 77

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 4.924226377441826e-17 + 1.4997740609555208e-16im
                   1.0 - 1.4997740609555203e-16im

"time = 2"

2-element Vector{Float64}:
 2.3165242354795865e-5
 0.9999768347576452

2-element Vector{ComplexF64}:
 0.00019719922385341216 - 2.4667163003664845e-18im
     0.9998028007761467 + 2.466716300366687e-18im

"time = 3"

2-element Vector{Float64}:
 5.609771535952296e-5
 0.9999439022846405

2-element Vector{ComplexF64}:
 0.0002545436847624392 + 3.9789037139219945e-16im
    0.9997454563152375 - 3.9789037139219945e-16im

"time = 4"

2-element Vector{Float64}:
 7.225100984969452e-5
 0.9999277489901502

2-element Vector{ComplexF64}:
 0.000282019043870613 - 4.34935976359342e-16im
   0.9997179809561294 + 4.349359763593419e-16im

"time = 5"

2-element Vector{Float64}:
 -0.00032510668497936086
  1.0003251066849794

2-element Vector{ComplexF64}:
 -0.000225581442816993 + 2.155484885858117e-16im
    1.0002255814428171 - 2.1554848858581164e-16im

Indexed Edge 20 => 19 with index 78

"time = 1"

2-element Vector{Float64}:
 0.0
 1.0

2-element Vector{ComplexF64}:
 -1.4922734048954698e-16 + 5.020234114983386e-17im
      1.0000000000000002 - 5.020234114983413e-17im

"time = 2"

2-element Vector{Float64}:
 2.3166762882395996e-5
 0.9999768332371176

2-element Vector{ComplexF64}:
 0.00019721201329851406 + 1.0992499080656018e-16im
     0.9998027879867013 - 1.0992499080656014e-16im

"time = 3"

2-element Vector{Float64}:
 5.615701173113146e-5
 0.9999438429882689

2-element Vector{ComplexF64}:
 0.0002545707540876793 - 1.6873581864746765e-16im
    0.9997454292459124 + 1.6873581864746856e-16im

"time = 4"

2-element Vector{Float64}:
 7.13215390207186e-5
 0.9999286784609792

2-element Vector{ComplexF64}:
 0.0002802951433819473 - 3.7898251996463604e-16im
    0.9997197048566181 + 3.7898251996463604e-16im

"time = 5"

2-element Vector{Float64}:
 -0.00030156394853032625
  1.0003015639485304

2-element Vector{ComplexF64}:
 -0.00019792176131370253 + 1.2801414697766628e-16im
      1.0001979217613137 - 1.2801414697766623e-16im